// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/service/ticket/producer.go
//
// Generated by this command:
//
//	mockgen -source=./internal/service/ticket/producer.go -package=ticketmocks -destination=./internal/service/ticket/mocks/producer.mock.go TicketEventProducer
//

// Package ticketmocks is a generated GoMock package.
package ticketmocks

import (
	context "context"
	reflect "reflect"

	event "github.com/Duke1616/eflow/internal/event"
	gomock "go.uber.org/mock/gomock"
)

// MockTicketEventProducer is a mock of TicketEventProducer interface.
type MockTicketEventProducer struct {
	ctrl     *gomock.Controller
	recorder *MockTicketEventProducerMockRecorder
	isgomock struct{}
}

// MockTicketEventProducerMockRecorder is the mock recorder for MockTicketEventProducer.
type MockTicketEventProducerMockRecorder struct {
	mock *MockTicketEventProducer
}

// NewMockTicketEventProducer creates a new mock instance.
func NewMockTicketEventProducer(ctrl *gomock.Controller) *MockTicketEventProducer {
	mock := &MockTicketEventProducer{ctrl: ctrl}
	mock.recorder = &MockTicketEventProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTicketEventProducer) EXPECT() *MockTicketEventProducerMockRecorder {
	return m.recorder
}

// Produce mocks base method.
func (m *MockTicketEventProducer) Produce(ctx context.Context, evt event.TicketEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Produce", ctx, evt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Produce indicates an expected call of Produce.
func (mr *MockTicketEventProducerMockRecorder) Produce(ctx, evt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Produce", reflect.TypeOf((*MockTicketEventProducer)(nil).Produce), ctx, evt)
}
