// Code generated by MockGen. DO NOT EDIT.
// Source: ./template.go
//
// Generated by this command:
//
//	mockgen -source=./template.go -package=repomocks -destination=./mocks/template_repo.mock.go -typed ITemplateRepository
//

// Package repomocks is a generated GoMock package.
package repomocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Duke1616/eflow/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockITemplateCoreRepository is a mock of ITemplateCoreRepository interface.
type MockITemplateCoreRepository struct {
	ctrl     *gomock.Controller
	recorder *MockITemplateCoreRepositoryMockRecorder
	isgomock struct{}
}

// MockITemplateCoreRepositoryMockRecorder is the mock recorder for MockITemplateCoreRepository.
type MockITemplateCoreRepositoryMockRecorder struct {
	mock *MockITemplateCoreRepository
}

// NewMockITemplateCoreRepository creates a new mock instance.
func NewMockITemplateCoreRepository(ctrl *gomock.Controller) *MockITemplateCoreRepository {
	mock := &MockITemplateCoreRepository{ctrl: ctrl}
	mock.recorder = &MockITemplateCoreRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITemplateCoreRepository) EXPECT() *MockITemplateCoreRepositoryMockRecorder {
	return m.recorder
}

// CreateTemplate mocks base method.
func (m *MockITemplateCoreRepository) CreateTemplate(ctx context.Context, req domain.Template) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTemplate", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTemplate indicates an expected call of CreateTemplate.
func (mr *MockITemplateCoreRepositoryMockRecorder) CreateTemplate(ctx, req any) *MockITemplateCoreRepositoryCreateTemplateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTemplate", reflect.TypeOf((*MockITemplateCoreRepository)(nil).CreateTemplate), ctx, req)
	return &MockITemplateCoreRepositoryCreateTemplateCall{Call: call}
}

// MockITemplateCoreRepositoryCreateTemplateCall wrap *gomock.Call
type MockITemplateCoreRepositoryCreateTemplateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITemplateCoreRepositoryCreateTemplateCall) Return(arg0 int64, arg1 error) *MockITemplateCoreRepositoryCreateTemplateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITemplateCoreRepositoryCreateTemplateCall) Do(f func(context.Context, domain.Template) (int64, error)) *MockITemplateCoreRepositoryCreateTemplateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITemplateCoreRepositoryCreateTemplateCall) DoAndReturn(f func(context.Context, domain.Template) (int64, error)) *MockITemplateCoreRepositoryCreateTemplateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteTemplate mocks base method.
func (m *MockITemplateCoreRepository) DeleteTemplate(ctx context.Context, id int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTemplate", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTemplate indicates an expected call of DeleteTemplate.
func (mr *MockITemplateCoreRepositoryMockRecorder) DeleteTemplate(ctx, id any) *MockITemplateCoreRepositoryDeleteTemplateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTemplate", reflect.TypeOf((*MockITemplateCoreRepository)(nil).DeleteTemplate), ctx, id)
	return &MockITemplateCoreRepositoryDeleteTemplateCall{Call: call}
}

// MockITemplateCoreRepositoryDeleteTemplateCall wrap *gomock.Call
type MockITemplateCoreRepositoryDeleteTemplateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITemplateCoreRepositoryDeleteTemplateCall) Return(arg0 int64, arg1 error) *MockITemplateCoreRepositoryDeleteTemplateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITemplateCoreRepositoryDeleteTemplateCall) Do(f func(context.Context, int64) (int64, error)) *MockITemplateCoreRepositoryDeleteTemplateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITemplateCoreRepositoryDeleteTemplateCall) DoAndReturn(f func(context.Context, int64) (int64, error)) *MockITemplateCoreRepositoryDeleteTemplateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DetailTemplate mocks base method.
func (m *MockITemplateCoreRepository) DetailTemplate(ctx context.Context, id int64) (domain.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetailTemplate", ctx, id)
	ret0, _ := ret[0].(domain.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DetailTemplate indicates an expected call of DetailTemplate.
func (mr *MockITemplateCoreRepositoryMockRecorder) DetailTemplate(ctx, id any) *MockITemplateCoreRepositoryDetailTemplateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetailTemplate", reflect.TypeOf((*MockITemplateCoreRepository)(nil).DetailTemplate), ctx, id)
	return &MockITemplateCoreRepositoryDetailTemplateCall{Call: call}
}

// MockITemplateCoreRepositoryDetailTemplateCall wrap *gomock.Call
type MockITemplateCoreRepositoryDetailTemplateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITemplateCoreRepositoryDetailTemplateCall) Return(arg0 domain.Template, arg1 error) *MockITemplateCoreRepositoryDetailTemplateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITemplateCoreRepositoryDetailTemplateCall) Do(f func(context.Context, int64) (domain.Template, error)) *MockITemplateCoreRepositoryDetailTemplateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITemplateCoreRepositoryDetailTemplateCall) DoAndReturn(f func(context.Context, int64) (domain.Template, error)) *MockITemplateCoreRepositoryDetailTemplateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DetailTemplateByExternalTemplateId mocks base method.
func (m *MockITemplateCoreRepository) DetailTemplateByExternalTemplateId(ctx context.Context, externalId string) (domain.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetailTemplateByExternalTemplateId", ctx, externalId)
	ret0, _ := ret[0].(domain.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DetailTemplateByExternalTemplateId indicates an expected call of DetailTemplateByExternalTemplateId.
func (mr *MockITemplateCoreRepositoryMockRecorder) DetailTemplateByExternalTemplateId(ctx, externalId any) *MockITemplateCoreRepositoryDetailTemplateByExternalTemplateIdCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetailTemplateByExternalTemplateId", reflect.TypeOf((*MockITemplateCoreRepository)(nil).DetailTemplateByExternalTemplateId), ctx, externalId)
	return &MockITemplateCoreRepositoryDetailTemplateByExternalTemplateIdCall{Call: call}
}

// MockITemplateCoreRepositoryDetailTemplateByExternalTemplateIdCall wrap *gomock.Call
type MockITemplateCoreRepositoryDetailTemplateByExternalTemplateIdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITemplateCoreRepositoryDetailTemplateByExternalTemplateIdCall) Return(arg0 domain.Template, arg1 error) *MockITemplateCoreRepositoryDetailTemplateByExternalTemplateIdCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITemplateCoreRepositoryDetailTemplateByExternalTemplateIdCall) Do(f func(context.Context, string) (domain.Template, error)) *MockITemplateCoreRepositoryDetailTemplateByExternalTemplateIdCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITemplateCoreRepositoryDetailTemplateByExternalTemplateIdCall) DoAndReturn(f func(context.Context, string) (domain.Template, error)) *MockITemplateCoreRepositoryDetailTemplateByExternalTemplateIdCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindByExternalTemplateId mocks base method.
func (m *MockITemplateCoreRepository) FindByExternalTemplateId(ctx context.Context, externalTemplateId string) (domain.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByExternalTemplateId", ctx, externalTemplateId)
	ret0, _ := ret[0].(domain.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByExternalTemplateId indicates an expected call of FindByExternalTemplateId.
func (mr *MockITemplateCoreRepositoryMockRecorder) FindByExternalTemplateId(ctx, externalTemplateId any) *MockITemplateCoreRepositoryFindByExternalTemplateIdCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByExternalTemplateId", reflect.TypeOf((*MockITemplateCoreRepository)(nil).FindByExternalTemplateId), ctx, externalTemplateId)
	return &MockITemplateCoreRepositoryFindByExternalTemplateIdCall{Call: call}
}

// MockITemplateCoreRepositoryFindByExternalTemplateIdCall wrap *gomock.Call
type MockITemplateCoreRepositoryFindByExternalTemplateIdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITemplateCoreRepositoryFindByExternalTemplateIdCall) Return(arg0 domain.Template, arg1 error) *MockITemplateCoreRepositoryFindByExternalTemplateIdCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITemplateCoreRepositoryFindByExternalTemplateIdCall) Do(f func(context.Context, string) (domain.Template, error)) *MockITemplateCoreRepositoryFindByExternalTemplateIdCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITemplateCoreRepositoryFindByExternalTemplateIdCall) DoAndReturn(f func(context.Context, string) (domain.Template, error)) *MockITemplateCoreRepositoryFindByExternalTemplateIdCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindByHash mocks base method.
func (m *MockITemplateCoreRepository) FindByHash(ctx context.Context, hash string) (domain.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByHash", ctx, hash)
	ret0, _ := ret[0].(domain.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByHash indicates an expected call of FindByHash.
func (mr *MockITemplateCoreRepositoryMockRecorder) FindByHash(ctx, hash any) *MockITemplateCoreRepositoryFindByHashCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByHash", reflect.TypeOf((*MockITemplateCoreRepository)(nil).FindByHash), ctx, hash)
	return &MockITemplateCoreRepositoryFindByHashCall{Call: call}
}

// MockITemplateCoreRepositoryFindByHashCall wrap *gomock.Call
type MockITemplateCoreRepositoryFindByHashCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITemplateCoreRepositoryFindByHashCall) Return(arg0 domain.Template, arg1 error) *MockITemplateCoreRepositoryFindByHashCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITemplateCoreRepositoryFindByHashCall) Do(f func(context.Context, string) (domain.Template, error)) *MockITemplateCoreRepositoryFindByHashCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITemplateCoreRepositoryFindByHashCall) DoAndReturn(f func(context.Context, string) (domain.Template, error)) *MockITemplateCoreRepositoryFindByHashCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindByTemplateIds mocks base method.
func (m *MockITemplateCoreRepository) FindByTemplateIds(ctx context.Context, ids []int64) ([]domain.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTemplateIds", ctx, ids)
	ret0, _ := ret[0].([]domain.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTemplateIds indicates an expected call of FindByTemplateIds.
func (mr *MockITemplateCoreRepositoryMockRecorder) FindByTemplateIds(ctx, ids any) *MockITemplateCoreRepositoryFindByTemplateIdsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTemplateIds", reflect.TypeOf((*MockITemplateCoreRepository)(nil).FindByTemplateIds), ctx, ids)
	return &MockITemplateCoreRepositoryFindByTemplateIdsCall{Call: call}
}

// MockITemplateCoreRepositoryFindByTemplateIdsCall wrap *gomock.Call
type MockITemplateCoreRepositoryFindByTemplateIdsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITemplateCoreRepositoryFindByTemplateIdsCall) Return(arg0 []domain.Template, arg1 error) *MockITemplateCoreRepositoryFindByTemplateIdsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITemplateCoreRepositoryFindByTemplateIdsCall) Do(f func(context.Context, []int64) ([]domain.Template, error)) *MockITemplateCoreRepositoryFindByTemplateIdsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITemplateCoreRepositoryFindByTemplateIdsCall) DoAndReturn(f func(context.Context, []int64) ([]domain.Template, error)) *MockITemplateCoreRepositoryFindByTemplateIdsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByWorkflowId mocks base method.
func (m *MockITemplateCoreRepository) GetByWorkflowId(ctx context.Context, workflowId int64) ([]domain.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByWorkflowId", ctx, workflowId)
	ret0, _ := ret[0].([]domain.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByWorkflowId indicates an expected call of GetByWorkflowId.
func (mr *MockITemplateCoreRepositoryMockRecorder) GetByWorkflowId(ctx, workflowId any) *MockITemplateCoreRepositoryGetByWorkflowIdCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByWorkflowId", reflect.TypeOf((*MockITemplateCoreRepository)(nil).GetByWorkflowId), ctx, workflowId)
	return &MockITemplateCoreRepositoryGetByWorkflowIdCall{Call: call}
}

// MockITemplateCoreRepositoryGetByWorkflowIdCall wrap *gomock.Call
type MockITemplateCoreRepositoryGetByWorkflowIdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITemplateCoreRepositoryGetByWorkflowIdCall) Return(arg0 []domain.Template, arg1 error) *MockITemplateCoreRepositoryGetByWorkflowIdCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITemplateCoreRepositoryGetByWorkflowIdCall) Do(f func(context.Context, int64) ([]domain.Template, error)) *MockITemplateCoreRepositoryGetByWorkflowIdCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITemplateCoreRepositoryGetByWorkflowIdCall) DoAndReturn(f func(context.Context, int64) ([]domain.Template, error)) *MockITemplateCoreRepositoryGetByWorkflowIdCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListTemplate mocks base method.
func (m *MockITemplateCoreRepository) ListTemplate(ctx context.Context, groupId int64, keyword string, offset, limit int64) ([]domain.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTemplate", ctx, groupId, keyword, offset, limit)
	ret0, _ := ret[0].([]domain.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTemplate indicates an expected call of ListTemplate.
func (mr *MockITemplateCoreRepositoryMockRecorder) ListTemplate(ctx, groupId, keyword, offset, limit any) *MockITemplateCoreRepositoryListTemplateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTemplate", reflect.TypeOf((*MockITemplateCoreRepository)(nil).ListTemplate), ctx, groupId, keyword, offset, limit)
	return &MockITemplateCoreRepositoryListTemplateCall{Call: call}
}

// MockITemplateCoreRepositoryListTemplateCall wrap *gomock.Call
type MockITemplateCoreRepositoryListTemplateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITemplateCoreRepositoryListTemplateCall) Return(arg0 []domain.Template, arg1 error) *MockITemplateCoreRepositoryListTemplateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITemplateCoreRepositoryListTemplateCall) Do(f func(context.Context, int64, string, int64, int64) ([]domain.Template, error)) *MockITemplateCoreRepositoryListTemplateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITemplateCoreRepositoryListTemplateCall) DoAndReturn(f func(context.Context, int64, string, int64, int64) ([]domain.Template, error)) *MockITemplateCoreRepositoryListTemplateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Total mocks base method.
func (m *MockITemplateCoreRepository) Total(ctx context.Context, groupId int64, keyword string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Total", ctx, groupId, keyword)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Total indicates an expected call of Total.
func (mr *MockITemplateCoreRepositoryMockRecorder) Total(ctx, groupId, keyword any) *MockITemplateCoreRepositoryTotalCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Total", reflect.TypeOf((*MockITemplateCoreRepository)(nil).Total), ctx, groupId, keyword)
	return &MockITemplateCoreRepositoryTotalCall{Call: call}
}

// MockITemplateCoreRepositoryTotalCall wrap *gomock.Call
type MockITemplateCoreRepositoryTotalCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITemplateCoreRepositoryTotalCall) Return(arg0 int64, arg1 error) *MockITemplateCoreRepositoryTotalCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITemplateCoreRepositoryTotalCall) Do(f func(context.Context, int64, string) (int64, error)) *MockITemplateCoreRepositoryTotalCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITemplateCoreRepositoryTotalCall) DoAndReturn(f func(context.Context, int64, string) (int64, error)) *MockITemplateCoreRepositoryTotalCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateTemplate mocks base method.
func (m *MockITemplateCoreRepository) UpdateTemplate(ctx context.Context, req domain.Template) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTemplate", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTemplate indicates an expected call of UpdateTemplate.
func (mr *MockITemplateCoreRepositoryMockRecorder) UpdateTemplate(ctx, req any) *MockITemplateCoreRepositoryUpdateTemplateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTemplate", reflect.TypeOf((*MockITemplateCoreRepository)(nil).UpdateTemplate), ctx, req)
	return &MockITemplateCoreRepositoryUpdateTemplateCall{Call: call}
}

// MockITemplateCoreRepositoryUpdateTemplateCall wrap *gomock.Call
type MockITemplateCoreRepositoryUpdateTemplateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITemplateCoreRepositoryUpdateTemplateCall) Return(arg0 int64, arg1 error) *MockITemplateCoreRepositoryUpdateTemplateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITemplateCoreRepositoryUpdateTemplateCall) Do(f func(context.Context, domain.Template) (int64, error)) *MockITemplateCoreRepositoryUpdateTemplateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITemplateCoreRepositoryUpdateTemplateCall) DoAndReturn(f func(context.Context, domain.Template) (int64, error)) *MockITemplateCoreRepositoryUpdateTemplateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockITemplateGroupRepository is a mock of ITemplateGroupRepository interface.
type MockITemplateGroupRepository struct {
	ctrl     *gomock.Controller
	recorder *MockITemplateGroupRepositoryMockRecorder
	isgomock struct{}
}

// MockITemplateGroupRepositoryMockRecorder is the mock recorder for MockITemplateGroupRepository.
type MockITemplateGroupRepositoryMockRecorder struct {
	mock *MockITemplateGroupRepository
}

// NewMockITemplateGroupRepository creates a new mock instance.
func NewMockITemplateGroupRepository(ctrl *gomock.Controller) *MockITemplateGroupRepository {
	mock := &MockITemplateGroupRepository{ctrl: ctrl}
	mock.recorder = &MockITemplateGroupRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITemplateGroupRepository) EXPECT() *MockITemplateGroupRepositoryMockRecorder {
	return m.recorder
}

// CreateGroup mocks base method.
func (m *MockITemplateGroupRepository) CreateGroup(ctx context.Context, req domain.TemplateGroup) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGroup", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGroup indicates an expected call of CreateGroup.
func (mr *MockITemplateGroupRepositoryMockRecorder) CreateGroup(ctx, req any) *MockITemplateGroupRepositoryCreateGroupCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGroup", reflect.TypeOf((*MockITemplateGroupRepository)(nil).CreateGroup), ctx, req)
	return &MockITemplateGroupRepositoryCreateGroupCall{Call: call}
}

// MockITemplateGroupRepositoryCreateGroupCall wrap *gomock.Call
type MockITemplateGroupRepositoryCreateGroupCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITemplateGroupRepositoryCreateGroupCall) Return(arg0 int64, arg1 error) *MockITemplateGroupRepositoryCreateGroupCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITemplateGroupRepositoryCreateGroupCall) Do(f func(context.Context, domain.TemplateGroup) (int64, error)) *MockITemplateGroupRepositoryCreateGroupCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITemplateGroupRepositoryCreateGroupCall) DoAndReturn(f func(context.Context, domain.TemplateGroup) (int64, error)) *MockITemplateGroupRepositoryCreateGroupCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteGroup mocks base method.
func (m *MockITemplateGroupRepository) DeleteGroup(ctx context.Context, id int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGroup", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteGroup indicates an expected call of DeleteGroup.
func (mr *MockITemplateGroupRepositoryMockRecorder) DeleteGroup(ctx, id any) *MockITemplateGroupRepositoryDeleteGroupCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGroup", reflect.TypeOf((*MockITemplateGroupRepository)(nil).DeleteGroup), ctx, id)
	return &MockITemplateGroupRepositoryDeleteGroupCall{Call: call}
}

// MockITemplateGroupRepositoryDeleteGroupCall wrap *gomock.Call
type MockITemplateGroupRepositoryDeleteGroupCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITemplateGroupRepositoryDeleteGroupCall) Return(arg0 int64, arg1 error) *MockITemplateGroupRepositoryDeleteGroupCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITemplateGroupRepositoryDeleteGroupCall) Do(f func(context.Context, int64) (int64, error)) *MockITemplateGroupRepositoryDeleteGroupCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITemplateGroupRepositoryDeleteGroupCall) DoAndReturn(f func(context.Context, int64) (int64, error)) *MockITemplateGroupRepositoryDeleteGroupCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListGroup mocks base method.
func (m *MockITemplateGroupRepository) ListGroup(ctx context.Context, offset, limit int64) ([]domain.TemplateGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGroup", ctx, offset, limit)
	ret0, _ := ret[0].([]domain.TemplateGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGroup indicates an expected call of ListGroup.
func (mr *MockITemplateGroupRepositoryMockRecorder) ListGroup(ctx, offset, limit any) *MockITemplateGroupRepositoryListGroupCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGroup", reflect.TypeOf((*MockITemplateGroupRepository)(nil).ListGroup), ctx, offset, limit)
	return &MockITemplateGroupRepositoryListGroupCall{Call: call}
}

// MockITemplateGroupRepositoryListGroupCall wrap *gomock.Call
type MockITemplateGroupRepositoryListGroupCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITemplateGroupRepositoryListGroupCall) Return(arg0 []domain.TemplateGroup, arg1 error) *MockITemplateGroupRepositoryListGroupCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITemplateGroupRepositoryListGroupCall) Do(f func(context.Context, int64, int64) ([]domain.TemplateGroup, error)) *MockITemplateGroupRepositoryListGroupCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITemplateGroupRepositoryListGroupCall) DoAndReturn(f func(context.Context, int64, int64) ([]domain.TemplateGroup, error)) *MockITemplateGroupRepositoryListGroupCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListGroupSummaries mocks base method.
func (m *MockITemplateGroupRepository) ListGroupSummaries(ctx context.Context) ([]domain.TemplateGroupSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGroupSummaries", ctx)
	ret0, _ := ret[0].([]domain.TemplateGroupSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGroupSummaries indicates an expected call of ListGroupSummaries.
func (mr *MockITemplateGroupRepositoryMockRecorder) ListGroupSummaries(ctx any) *MockITemplateGroupRepositoryListGroupSummariesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGroupSummaries", reflect.TypeOf((*MockITemplateGroupRepository)(nil).ListGroupSummaries), ctx)
	return &MockITemplateGroupRepositoryListGroupSummariesCall{Call: call}
}

// MockITemplateGroupRepositoryListGroupSummariesCall wrap *gomock.Call
type MockITemplateGroupRepositoryListGroupSummariesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITemplateGroupRepositoryListGroupSummariesCall) Return(arg0 []domain.TemplateGroupSummary, arg1 error) *MockITemplateGroupRepositoryListGroupSummariesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITemplateGroupRepositoryListGroupSummariesCall) Do(f func(context.Context) ([]domain.TemplateGroupSummary, error)) *MockITemplateGroupRepositoryListGroupSummariesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITemplateGroupRepositoryListGroupSummariesCall) DoAndReturn(f func(context.Context) ([]domain.TemplateGroupSummary, error)) *MockITemplateGroupRepositoryListGroupSummariesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// TotalGroup mocks base method.
func (m *MockITemplateGroupRepository) TotalGroup(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TotalGroup", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TotalGroup indicates an expected call of TotalGroup.
func (mr *MockITemplateGroupRepositoryMockRecorder) TotalGroup(ctx any) *MockITemplateGroupRepositoryTotalGroupCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TotalGroup", reflect.TypeOf((*MockITemplateGroupRepository)(nil).TotalGroup), ctx)
	return &MockITemplateGroupRepositoryTotalGroupCall{Call: call}
}

// MockITemplateGroupRepositoryTotalGroupCall wrap *gomock.Call
type MockITemplateGroupRepositoryTotalGroupCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITemplateGroupRepositoryTotalGroupCall) Return(arg0 int64, arg1 error) *MockITemplateGroupRepositoryTotalGroupCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITemplateGroupRepositoryTotalGroupCall) Do(f func(context.Context) (int64, error)) *MockITemplateGroupRepositoryTotalGroupCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITemplateGroupRepositoryTotalGroupCall) DoAndReturn(f func(context.Context) (int64, error)) *MockITemplateGroupRepositoryTotalGroupCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateGroup mocks base method.
func (m *MockITemplateGroupRepository) UpdateGroup(ctx context.Context, req domain.TemplateGroup) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGroup", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateGroup indicates an expected call of UpdateGroup.
func (mr *MockITemplateGroupRepositoryMockRecorder) UpdateGroup(ctx, req any) *MockITemplateGroupRepositoryUpdateGroupCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGroup", reflect.TypeOf((*MockITemplateGroupRepository)(nil).UpdateGroup), ctx, req)
	return &MockITemplateGroupRepositoryUpdateGroupCall{Call: call}
}

// MockITemplateGroupRepositoryUpdateGroupCall wrap *gomock.Call
type MockITemplateGroupRepositoryUpdateGroupCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITemplateGroupRepositoryUpdateGroupCall) Return(arg0 int64, arg1 error) *MockITemplateGroupRepositoryUpdateGroupCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITemplateGroupRepositoryUpdateGroupCall) Do(f func(context.Context, domain.TemplateGroup) (int64, error)) *MockITemplateGroupRepositoryUpdateGroupCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITemplateGroupRepositoryUpdateGroupCall) DoAndReturn(f func(context.Context, domain.TemplateGroup) (int64, error)) *MockITemplateGroupRepositoryUpdateGroupCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockITemplateFavoriteRepository is a mock of ITemplateFavoriteRepository interface.
type MockITemplateFavoriteRepository struct {
	ctrl     *gomock.Controller
	recorder *MockITemplateFavoriteRepositoryMockRecorder
	isgomock struct{}
}

// MockITemplateFavoriteRepositoryMockRecorder is the mock recorder for MockITemplateFavoriteRepository.
type MockITemplateFavoriteRepositoryMockRecorder struct {
	mock *MockITemplateFavoriteRepository
}

// NewMockITemplateFavoriteRepository creates a new mock instance.
func NewMockITemplateFavoriteRepository(ctrl *gomock.Controller) *MockITemplateFavoriteRepository {
	mock := &MockITemplateFavoriteRepository{ctrl: ctrl}
	mock.recorder = &MockITemplateFavoriteRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITemplateFavoriteRepository) EXPECT() *MockITemplateFavoriteRepositoryMockRecorder {
	return m.recorder
}

// ListFavoriteTemplates mocks base method.
func (m *MockITemplateFavoriteRepository) ListFavoriteTemplates(ctx context.Context, userId int64) ([]domain.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFavoriteTemplates", ctx, userId)
	ret0, _ := ret[0].([]domain.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFavoriteTemplates indicates an expected call of ListFavoriteTemplates.
func (mr *MockITemplateFavoriteRepositoryMockRecorder) ListFavoriteTemplates(ctx, userId any) *MockITemplateFavoriteRepositoryListFavoriteTemplatesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFavoriteTemplates", reflect.TypeOf((*MockITemplateFavoriteRepository)(nil).ListFavoriteTemplates), ctx, userId)
	return &MockITemplateFavoriteRepositoryListFavoriteTemplatesCall{Call: call}
}

// MockITemplateFavoriteRepositoryListFavoriteTemplatesCall wrap *gomock.Call
type MockITemplateFavoriteRepositoryListFavoriteTemplatesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITemplateFavoriteRepositoryListFavoriteTemplatesCall) Return(arg0 []domain.Template, arg1 error) *MockITemplateFavoriteRepositoryListFavoriteTemplatesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITemplateFavoriteRepositoryListFavoriteTemplatesCall) Do(f func(context.Context, int64) ([]domain.Template, error)) *MockITemplateFavoriteRepositoryListFavoriteTemplatesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITemplateFavoriteRepositoryListFavoriteTemplatesCall) DoAndReturn(f func(context.Context, int64) ([]domain.Template, error)) *MockITemplateFavoriteRepositoryListFavoriteTemplatesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ToggleFavorite mocks base method.
func (m *MockITemplateFavoriteRepository) ToggleFavorite(ctx context.Context, userId, templateId int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToggleFavorite", ctx, userId, templateId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToggleFavorite indicates an expected call of ToggleFavorite.
func (mr *MockITemplateFavoriteRepositoryMockRecorder) ToggleFavorite(ctx, userId, templateId any) *MockITemplateFavoriteRepositoryToggleFavoriteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToggleFavorite", reflect.TypeOf((*MockITemplateFavoriteRepository)(nil).ToggleFavorite), ctx, userId, templateId)
	return &MockITemplateFavoriteRepositoryToggleFavoriteCall{Call: call}
}

// MockITemplateFavoriteRepositoryToggleFavoriteCall wrap *gomock.Call
type MockITemplateFavoriteRepositoryToggleFavoriteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITemplateFavoriteRepositoryToggleFavoriteCall) Return(arg0 bool, arg1 error) *MockITemplateFavoriteRepositoryToggleFavoriteCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITemplateFavoriteRepositoryToggleFavoriteCall) Do(f func(context.Context, int64, int64) (bool, error)) *MockITemplateFavoriteRepositoryToggleFavoriteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITemplateFavoriteRepositoryToggleFavoriteCall) DoAndReturn(f func(context.Context, int64, int64) (bool, error)) *MockITemplateFavoriteRepositoryToggleFavoriteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockITemplateRepository is a mock of ITemplateRepository interface.
type MockITemplateRepository struct {
	ctrl     *gomock.Controller
	recorder *MockITemplateRepositoryMockRecorder
	isgomock struct{}
}

// MockITemplateRepositoryMockRecorder is the mock recorder for MockITemplateRepository.
type MockITemplateRepositoryMockRecorder struct {
	mock *MockITemplateRepository
}

// NewMockITemplateRepository creates a new mock instance.
func NewMockITemplateRepository(ctrl *gomock.Controller) *MockITemplateRepository {
	mock := &MockITemplateRepository{ctrl: ctrl}
	mock.recorder = &MockITemplateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITemplateRepository) EXPECT() *MockITemplateRepositoryMockRecorder {
	return m.recorder
}

// CreateGroup mocks base method.
func (m *MockITemplateRepository) CreateGroup(ctx context.Context, req domain.TemplateGroup) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGroup", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGroup indicates an expected call of CreateGroup.
func (mr *MockITemplateRepositoryMockRecorder) CreateGroup(ctx, req any) *MockITemplateRepositoryCreateGroupCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGroup", reflect.TypeOf((*MockITemplateRepository)(nil).CreateGroup), ctx, req)
	return &MockITemplateRepositoryCreateGroupCall{Call: call}
}

// MockITemplateRepositoryCreateGroupCall wrap *gomock.Call
type MockITemplateRepositoryCreateGroupCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITemplateRepositoryCreateGroupCall) Return(arg0 int64, arg1 error) *MockITemplateRepositoryCreateGroupCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITemplateRepositoryCreateGroupCall) Do(f func(context.Context, domain.TemplateGroup) (int64, error)) *MockITemplateRepositoryCreateGroupCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITemplateRepositoryCreateGroupCall) DoAndReturn(f func(context.Context, domain.TemplateGroup) (int64, error)) *MockITemplateRepositoryCreateGroupCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateTemplate mocks base method.
func (m *MockITemplateRepository) CreateTemplate(ctx context.Context, req domain.Template) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTemplate", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTemplate indicates an expected call of CreateTemplate.
func (mr *MockITemplateRepositoryMockRecorder) CreateTemplate(ctx, req any) *MockITemplateRepositoryCreateTemplateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTemplate", reflect.TypeOf((*MockITemplateRepository)(nil).CreateTemplate), ctx, req)
	return &MockITemplateRepositoryCreateTemplateCall{Call: call}
}

// MockITemplateRepositoryCreateTemplateCall wrap *gomock.Call
type MockITemplateRepositoryCreateTemplateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITemplateRepositoryCreateTemplateCall) Return(arg0 int64, arg1 error) *MockITemplateRepositoryCreateTemplateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITemplateRepositoryCreateTemplateCall) Do(f func(context.Context, domain.Template) (int64, error)) *MockITemplateRepositoryCreateTemplateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITemplateRepositoryCreateTemplateCall) DoAndReturn(f func(context.Context, domain.Template) (int64, error)) *MockITemplateRepositoryCreateTemplateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteGroup mocks base method.
func (m *MockITemplateRepository) DeleteGroup(ctx context.Context, id int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGroup", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteGroup indicates an expected call of DeleteGroup.
func (mr *MockITemplateRepositoryMockRecorder) DeleteGroup(ctx, id any) *MockITemplateRepositoryDeleteGroupCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGroup", reflect.TypeOf((*MockITemplateRepository)(nil).DeleteGroup), ctx, id)
	return &MockITemplateRepositoryDeleteGroupCall{Call: call}
}

// MockITemplateRepositoryDeleteGroupCall wrap *gomock.Call
type MockITemplateRepositoryDeleteGroupCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITemplateRepositoryDeleteGroupCall) Return(arg0 int64, arg1 error) *MockITemplateRepositoryDeleteGroupCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITemplateRepositoryDeleteGroupCall) Do(f func(context.Context, int64) (int64, error)) *MockITemplateRepositoryDeleteGroupCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITemplateRepositoryDeleteGroupCall) DoAndReturn(f func(context.Context, int64) (int64, error)) *MockITemplateRepositoryDeleteGroupCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteTemplate mocks base method.
func (m *MockITemplateRepository) DeleteTemplate(ctx context.Context, id int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTemplate", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTemplate indicates an expected call of DeleteTemplate.
func (mr *MockITemplateRepositoryMockRecorder) DeleteTemplate(ctx, id any) *MockITemplateRepositoryDeleteTemplateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTemplate", reflect.TypeOf((*MockITemplateRepository)(nil).DeleteTemplate), ctx, id)
	return &MockITemplateRepositoryDeleteTemplateCall{Call: call}
}

// MockITemplateRepositoryDeleteTemplateCall wrap *gomock.Call
type MockITemplateRepositoryDeleteTemplateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITemplateRepositoryDeleteTemplateCall) Return(arg0 int64, arg1 error) *MockITemplateRepositoryDeleteTemplateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITemplateRepositoryDeleteTemplateCall) Do(f func(context.Context, int64) (int64, error)) *MockITemplateRepositoryDeleteTemplateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITemplateRepositoryDeleteTemplateCall) DoAndReturn(f func(context.Context, int64) (int64, error)) *MockITemplateRepositoryDeleteTemplateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DetailTemplate mocks base method.
func (m *MockITemplateRepository) DetailTemplate(ctx context.Context, id int64) (domain.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetailTemplate", ctx, id)
	ret0, _ := ret[0].(domain.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DetailTemplate indicates an expected call of DetailTemplate.
func (mr *MockITemplateRepositoryMockRecorder) DetailTemplate(ctx, id any) *MockITemplateRepositoryDetailTemplateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetailTemplate", reflect.TypeOf((*MockITemplateRepository)(nil).DetailTemplate), ctx, id)
	return &MockITemplateRepositoryDetailTemplateCall{Call: call}
}

// MockITemplateRepositoryDetailTemplateCall wrap *gomock.Call
type MockITemplateRepositoryDetailTemplateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITemplateRepositoryDetailTemplateCall) Return(arg0 domain.Template, arg1 error) *MockITemplateRepositoryDetailTemplateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITemplateRepositoryDetailTemplateCall) Do(f func(context.Context, int64) (domain.Template, error)) *MockITemplateRepositoryDetailTemplateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITemplateRepositoryDetailTemplateCall) DoAndReturn(f func(context.Context, int64) (domain.Template, error)) *MockITemplateRepositoryDetailTemplateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DetailTemplateByExternalTemplateId mocks base method.
func (m *MockITemplateRepository) DetailTemplateByExternalTemplateId(ctx context.Context, externalId string) (domain.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetailTemplateByExternalTemplateId", ctx, externalId)
	ret0, _ := ret[0].(domain.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DetailTemplateByExternalTemplateId indicates an expected call of DetailTemplateByExternalTemplateId.
func (mr *MockITemplateRepositoryMockRecorder) DetailTemplateByExternalTemplateId(ctx, externalId any) *MockITemplateRepositoryDetailTemplateByExternalTemplateIdCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetailTemplateByExternalTemplateId", reflect.TypeOf((*MockITemplateRepository)(nil).DetailTemplateByExternalTemplateId), ctx, externalId)
	return &MockITemplateRepositoryDetailTemplateByExternalTemplateIdCall{Call: call}
}

// MockITemplateRepositoryDetailTemplateByExternalTemplateIdCall wrap *gomock.Call
type MockITemplateRepositoryDetailTemplateByExternalTemplateIdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITemplateRepositoryDetailTemplateByExternalTemplateIdCall) Return(arg0 domain.Template, arg1 error) *MockITemplateRepositoryDetailTemplateByExternalTemplateIdCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITemplateRepositoryDetailTemplateByExternalTemplateIdCall) Do(f func(context.Context, string) (domain.Template, error)) *MockITemplateRepositoryDetailTemplateByExternalTemplateIdCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITemplateRepositoryDetailTemplateByExternalTemplateIdCall) DoAndReturn(f func(context.Context, string) (domain.Template, error)) *MockITemplateRepositoryDetailTemplateByExternalTemplateIdCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindByExternalTemplateId mocks base method.
func (m *MockITemplateRepository) FindByExternalTemplateId(ctx context.Context, externalTemplateId string) (domain.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByExternalTemplateId", ctx, externalTemplateId)
	ret0, _ := ret[0].(domain.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByExternalTemplateId indicates an expected call of FindByExternalTemplateId.
func (mr *MockITemplateRepositoryMockRecorder) FindByExternalTemplateId(ctx, externalTemplateId any) *MockITemplateRepositoryFindByExternalTemplateIdCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByExternalTemplateId", reflect.TypeOf((*MockITemplateRepository)(nil).FindByExternalTemplateId), ctx, externalTemplateId)
	return &MockITemplateRepositoryFindByExternalTemplateIdCall{Call: call}
}

// MockITemplateRepositoryFindByExternalTemplateIdCall wrap *gomock.Call
type MockITemplateRepositoryFindByExternalTemplateIdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITemplateRepositoryFindByExternalTemplateIdCall) Return(arg0 domain.Template, arg1 error) *MockITemplateRepositoryFindByExternalTemplateIdCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITemplateRepositoryFindByExternalTemplateIdCall) Do(f func(context.Context, string) (domain.Template, error)) *MockITemplateRepositoryFindByExternalTemplateIdCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITemplateRepositoryFindByExternalTemplateIdCall) DoAndReturn(f func(context.Context, string) (domain.Template, error)) *MockITemplateRepositoryFindByExternalTemplateIdCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindByHash mocks base method.
func (m *MockITemplateRepository) FindByHash(ctx context.Context, hash string) (domain.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByHash", ctx, hash)
	ret0, _ := ret[0].(domain.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByHash indicates an expected call of FindByHash.
func (mr *MockITemplateRepositoryMockRecorder) FindByHash(ctx, hash any) *MockITemplateRepositoryFindByHashCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByHash", reflect.TypeOf((*MockITemplateRepository)(nil).FindByHash), ctx, hash)
	return &MockITemplateRepositoryFindByHashCall{Call: call}
}

// MockITemplateRepositoryFindByHashCall wrap *gomock.Call
type MockITemplateRepositoryFindByHashCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITemplateRepositoryFindByHashCall) Return(arg0 domain.Template, arg1 error) *MockITemplateRepositoryFindByHashCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITemplateRepositoryFindByHashCall) Do(f func(context.Context, string) (domain.Template, error)) *MockITemplateRepositoryFindByHashCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITemplateRepositoryFindByHashCall) DoAndReturn(f func(context.Context, string) (domain.Template, error)) *MockITemplateRepositoryFindByHashCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindByTemplateIds mocks base method.
func (m *MockITemplateRepository) FindByTemplateIds(ctx context.Context, ids []int64) ([]domain.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTemplateIds", ctx, ids)
	ret0, _ := ret[0].([]domain.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTemplateIds indicates an expected call of FindByTemplateIds.
func (mr *MockITemplateRepositoryMockRecorder) FindByTemplateIds(ctx, ids any) *MockITemplateRepositoryFindByTemplateIdsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTemplateIds", reflect.TypeOf((*MockITemplateRepository)(nil).FindByTemplateIds), ctx, ids)
	return &MockITemplateRepositoryFindByTemplateIdsCall{Call: call}
}

// MockITemplateRepositoryFindByTemplateIdsCall wrap *gomock.Call
type MockITemplateRepositoryFindByTemplateIdsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITemplateRepositoryFindByTemplateIdsCall) Return(arg0 []domain.Template, arg1 error) *MockITemplateRepositoryFindByTemplateIdsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITemplateRepositoryFindByTemplateIdsCall) Do(f func(context.Context, []int64) ([]domain.Template, error)) *MockITemplateRepositoryFindByTemplateIdsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITemplateRepositoryFindByTemplateIdsCall) DoAndReturn(f func(context.Context, []int64) ([]domain.Template, error)) *MockITemplateRepositoryFindByTemplateIdsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByWorkflowId mocks base method.
func (m *MockITemplateRepository) GetByWorkflowId(ctx context.Context, workflowId int64) ([]domain.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByWorkflowId", ctx, workflowId)
	ret0, _ := ret[0].([]domain.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByWorkflowId indicates an expected call of GetByWorkflowId.
func (mr *MockITemplateRepositoryMockRecorder) GetByWorkflowId(ctx, workflowId any) *MockITemplateRepositoryGetByWorkflowIdCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByWorkflowId", reflect.TypeOf((*MockITemplateRepository)(nil).GetByWorkflowId), ctx, workflowId)
	return &MockITemplateRepositoryGetByWorkflowIdCall{Call: call}
}

// MockITemplateRepositoryGetByWorkflowIdCall wrap *gomock.Call
type MockITemplateRepositoryGetByWorkflowIdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITemplateRepositoryGetByWorkflowIdCall) Return(arg0 []domain.Template, arg1 error) *MockITemplateRepositoryGetByWorkflowIdCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITemplateRepositoryGetByWorkflowIdCall) Do(f func(context.Context, int64) ([]domain.Template, error)) *MockITemplateRepositoryGetByWorkflowIdCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITemplateRepositoryGetByWorkflowIdCall) DoAndReturn(f func(context.Context, int64) ([]domain.Template, error)) *MockITemplateRepositoryGetByWorkflowIdCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListFavoriteTemplates mocks base method.
func (m *MockITemplateRepository) ListFavoriteTemplates(ctx context.Context, userId int64) ([]domain.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFavoriteTemplates", ctx, userId)
	ret0, _ := ret[0].([]domain.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFavoriteTemplates indicates an expected call of ListFavoriteTemplates.
func (mr *MockITemplateRepositoryMockRecorder) ListFavoriteTemplates(ctx, userId any) *MockITemplateRepositoryListFavoriteTemplatesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFavoriteTemplates", reflect.TypeOf((*MockITemplateRepository)(nil).ListFavoriteTemplates), ctx, userId)
	return &MockITemplateRepositoryListFavoriteTemplatesCall{Call: call}
}

// MockITemplateRepositoryListFavoriteTemplatesCall wrap *gomock.Call
type MockITemplateRepositoryListFavoriteTemplatesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITemplateRepositoryListFavoriteTemplatesCall) Return(arg0 []domain.Template, arg1 error) *MockITemplateRepositoryListFavoriteTemplatesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITemplateRepositoryListFavoriteTemplatesCall) Do(f func(context.Context, int64) ([]domain.Template, error)) *MockITemplateRepositoryListFavoriteTemplatesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITemplateRepositoryListFavoriteTemplatesCall) DoAndReturn(f func(context.Context, int64) ([]domain.Template, error)) *MockITemplateRepositoryListFavoriteTemplatesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListGroup mocks base method.
func (m *MockITemplateRepository) ListGroup(ctx context.Context, offset, limit int64) ([]domain.TemplateGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGroup", ctx, offset, limit)
	ret0, _ := ret[0].([]domain.TemplateGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGroup indicates an expected call of ListGroup.
func (mr *MockITemplateRepositoryMockRecorder) ListGroup(ctx, offset, limit any) *MockITemplateRepositoryListGroupCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGroup", reflect.TypeOf((*MockITemplateRepository)(nil).ListGroup), ctx, offset, limit)
	return &MockITemplateRepositoryListGroupCall{Call: call}
}

// MockITemplateRepositoryListGroupCall wrap *gomock.Call
type MockITemplateRepositoryListGroupCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITemplateRepositoryListGroupCall) Return(arg0 []domain.TemplateGroup, arg1 error) *MockITemplateRepositoryListGroupCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITemplateRepositoryListGroupCall) Do(f func(context.Context, int64, int64) ([]domain.TemplateGroup, error)) *MockITemplateRepositoryListGroupCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITemplateRepositoryListGroupCall) DoAndReturn(f func(context.Context, int64, int64) ([]domain.TemplateGroup, error)) *MockITemplateRepositoryListGroupCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListGroupSummaries mocks base method.
func (m *MockITemplateRepository) ListGroupSummaries(ctx context.Context) ([]domain.TemplateGroupSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGroupSummaries", ctx)
	ret0, _ := ret[0].([]domain.TemplateGroupSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGroupSummaries indicates an expected call of ListGroupSummaries.
func (mr *MockITemplateRepositoryMockRecorder) ListGroupSummaries(ctx any) *MockITemplateRepositoryListGroupSummariesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGroupSummaries", reflect.TypeOf((*MockITemplateRepository)(nil).ListGroupSummaries), ctx)
	return &MockITemplateRepositoryListGroupSummariesCall{Call: call}
}

// MockITemplateRepositoryListGroupSummariesCall wrap *gomock.Call
type MockITemplateRepositoryListGroupSummariesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITemplateRepositoryListGroupSummariesCall) Return(arg0 []domain.TemplateGroupSummary, arg1 error) *MockITemplateRepositoryListGroupSummariesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITemplateRepositoryListGroupSummariesCall) Do(f func(context.Context) ([]domain.TemplateGroupSummary, error)) *MockITemplateRepositoryListGroupSummariesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITemplateRepositoryListGroupSummariesCall) DoAndReturn(f func(context.Context) ([]domain.TemplateGroupSummary, error)) *MockITemplateRepositoryListGroupSummariesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListTemplate mocks base method.
func (m *MockITemplateRepository) ListTemplate(ctx context.Context, groupId int64, keyword string, offset, limit int64) ([]domain.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTemplate", ctx, groupId, keyword, offset, limit)
	ret0, _ := ret[0].([]domain.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTemplate indicates an expected call of ListTemplate.
func (mr *MockITemplateRepositoryMockRecorder) ListTemplate(ctx, groupId, keyword, offset, limit any) *MockITemplateRepositoryListTemplateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTemplate", reflect.TypeOf((*MockITemplateRepository)(nil).ListTemplate), ctx, groupId, keyword, offset, limit)
	return &MockITemplateRepositoryListTemplateCall{Call: call}
}

// MockITemplateRepositoryListTemplateCall wrap *gomock.Call
type MockITemplateRepositoryListTemplateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITemplateRepositoryListTemplateCall) Return(arg0 []domain.Template, arg1 error) *MockITemplateRepositoryListTemplateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITemplateRepositoryListTemplateCall) Do(f func(context.Context, int64, string, int64, int64) ([]domain.Template, error)) *MockITemplateRepositoryListTemplateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITemplateRepositoryListTemplateCall) DoAndReturn(f func(context.Context, int64, string, int64, int64) ([]domain.Template, error)) *MockITemplateRepositoryListTemplateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ToggleFavorite mocks base method.
func (m *MockITemplateRepository) ToggleFavorite(ctx context.Context, userId, templateId int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToggleFavorite", ctx, userId, templateId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToggleFavorite indicates an expected call of ToggleFavorite.
func (mr *MockITemplateRepositoryMockRecorder) ToggleFavorite(ctx, userId, templateId any) *MockITemplateRepositoryToggleFavoriteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToggleFavorite", reflect.TypeOf((*MockITemplateRepository)(nil).ToggleFavorite), ctx, userId, templateId)
	return &MockITemplateRepositoryToggleFavoriteCall{Call: call}
}

// MockITemplateRepositoryToggleFavoriteCall wrap *gomock.Call
type MockITemplateRepositoryToggleFavoriteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITemplateRepositoryToggleFavoriteCall) Return(arg0 bool, arg1 error) *MockITemplateRepositoryToggleFavoriteCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITemplateRepositoryToggleFavoriteCall) Do(f func(context.Context, int64, int64) (bool, error)) *MockITemplateRepositoryToggleFavoriteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITemplateRepositoryToggleFavoriteCall) DoAndReturn(f func(context.Context, int64, int64) (bool, error)) *MockITemplateRepositoryToggleFavoriteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Total mocks base method.
func (m *MockITemplateRepository) Total(ctx context.Context, groupId int64, keyword string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Total", ctx, groupId, keyword)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Total indicates an expected call of Total.
func (mr *MockITemplateRepositoryMockRecorder) Total(ctx, groupId, keyword any) *MockITemplateRepositoryTotalCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Total", reflect.TypeOf((*MockITemplateRepository)(nil).Total), ctx, groupId, keyword)
	return &MockITemplateRepositoryTotalCall{Call: call}
}

// MockITemplateRepositoryTotalCall wrap *gomock.Call
type MockITemplateRepositoryTotalCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITemplateRepositoryTotalCall) Return(arg0 int64, arg1 error) *MockITemplateRepositoryTotalCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITemplateRepositoryTotalCall) Do(f func(context.Context, int64, string) (int64, error)) *MockITemplateRepositoryTotalCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITemplateRepositoryTotalCall) DoAndReturn(f func(context.Context, int64, string) (int64, error)) *MockITemplateRepositoryTotalCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// TotalGroup mocks base method.
func (m *MockITemplateRepository) TotalGroup(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TotalGroup", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TotalGroup indicates an expected call of TotalGroup.
func (mr *MockITemplateRepositoryMockRecorder) TotalGroup(ctx any) *MockITemplateRepositoryTotalGroupCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TotalGroup", reflect.TypeOf((*MockITemplateRepository)(nil).TotalGroup), ctx)
	return &MockITemplateRepositoryTotalGroupCall{Call: call}
}

// MockITemplateRepositoryTotalGroupCall wrap *gomock.Call
type MockITemplateRepositoryTotalGroupCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITemplateRepositoryTotalGroupCall) Return(arg0 int64, arg1 error) *MockITemplateRepositoryTotalGroupCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITemplateRepositoryTotalGroupCall) Do(f func(context.Context) (int64, error)) *MockITemplateRepositoryTotalGroupCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITemplateRepositoryTotalGroupCall) DoAndReturn(f func(context.Context) (int64, error)) *MockITemplateRepositoryTotalGroupCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateGroup mocks base method.
func (m *MockITemplateRepository) UpdateGroup(ctx context.Context, req domain.TemplateGroup) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGroup", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateGroup indicates an expected call of UpdateGroup.
func (mr *MockITemplateRepositoryMockRecorder) UpdateGroup(ctx, req any) *MockITemplateRepositoryUpdateGroupCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGroup", reflect.TypeOf((*MockITemplateRepository)(nil).UpdateGroup), ctx, req)
	return &MockITemplateRepositoryUpdateGroupCall{Call: call}
}

// MockITemplateRepositoryUpdateGroupCall wrap *gomock.Call
type MockITemplateRepositoryUpdateGroupCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITemplateRepositoryUpdateGroupCall) Return(arg0 int64, arg1 error) *MockITemplateRepositoryUpdateGroupCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITemplateRepositoryUpdateGroupCall) Do(f func(context.Context, domain.TemplateGroup) (int64, error)) *MockITemplateRepositoryUpdateGroupCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITemplateRepositoryUpdateGroupCall) DoAndReturn(f func(context.Context, domain.TemplateGroup) (int64, error)) *MockITemplateRepositoryUpdateGroupCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateTemplate mocks base method.
func (m *MockITemplateRepository) UpdateTemplate(ctx context.Context, req domain.Template) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTemplate", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTemplate indicates an expected call of UpdateTemplate.
func (mr *MockITemplateRepositoryMockRecorder) UpdateTemplate(ctx, req any) *MockITemplateRepositoryUpdateTemplateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTemplate", reflect.TypeOf((*MockITemplateRepository)(nil).UpdateTemplate), ctx, req)
	return &MockITemplateRepositoryUpdateTemplateCall{Call: call}
}

// MockITemplateRepositoryUpdateTemplateCall wrap *gomock.Call
type MockITemplateRepositoryUpdateTemplateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockITemplateRepositoryUpdateTemplateCall) Return(arg0 int64, arg1 error) *MockITemplateRepositoryUpdateTemplateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockITemplateRepositoryUpdateTemplateCall) Do(f func(context.Context, domain.Template) (int64, error)) *MockITemplateRepositoryUpdateTemplateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockITemplateRepositoryUpdateTemplateCall) DoAndReturn(f func(context.Context, domain.Template) (int64, error)) *MockITemplateRepositoryUpdateTemplateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
