// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repository/ticket.go
//
// Generated by this command:
//
//	mockgen -source=./internal/repository/ticket.go -package=repomocks -destination=./internal/repository/mocks/ticket_repo.mock.go TicketRepository
//

// Package repomocks is a generated GoMock package.
package repomocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Duke1616/eflow/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockTicketRepository is a mock of TicketRepository interface.
type MockTicketRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTicketRepositoryMockRecorder
	isgomock struct{}
}

// MockTicketRepositoryMockRecorder is the mock recorder for MockTicketRepository.
type MockTicketRepositoryMockRecorder struct {
	mock *MockTicketRepository
}

// NewMockTicketRepository creates a new mock instance.
func NewMockTicketRepository(ctrl *gomock.Controller) *MockTicketRepository {
	mock := &MockTicketRepository{ctrl: ctrl}
	mock.recorder = &MockTicketRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTicketRepository) EXPECT() *MockTicketRepositoryMockRecorder {
	return m.recorder
}

// AccessibleDetailByProcessInstId mocks base method.
func (m *MockTicketRepository) AccessibleDetailByProcessInstId(ctx context.Context, instanceId int) (domain.Ticket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccessibleDetailByProcessInstId", ctx, instanceId)
	ret0, _ := ret[0].(domain.Ticket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AccessibleDetailByProcessInstId indicates an expected call of AccessibleDetailByProcessInstId.
func (mr *MockTicketRepositoryMockRecorder) AccessibleDetailByProcessInstId(ctx, instanceId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccessibleDetailByProcessInstId", reflect.TypeOf((*MockTicketRepository)(nil).AccessibleDetailByProcessInstId), ctx, instanceId)
}

// CountHistory mocks base method.
func (m *MockTicketRepository) CountHistory(ctx context.Context, userId string, status []int) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountHistory", ctx, userId, status)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountHistory indicates an expected call of CountHistory.
func (mr *MockTicketRepositoryMockRecorder) CountHistory(ctx, userId, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountHistory", reflect.TypeOf((*MockTicketRepository)(nil).CountHistory), ctx, userId, status)
}

// CountProcessStartFailed mocks base method.
func (m *MockTicketRepository) CountProcessStartFailed(ctx context.Context, userId string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountProcessStartFailed", ctx, userId)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountProcessStartFailed indicates an expected call of CountProcessStartFailed.
func (mr *MockTicketRepositoryMockRecorder) CountProcessStartFailed(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountProcessStartFailed", reflect.TypeOf((*MockTicketRepository)(nil).CountProcessStartFailed), ctx, userId)
}

// CountTicket mocks base method.
func (m *MockTicketRepository) CountTicket(ctx context.Context, userId string, status []int) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountTicket", ctx, userId, status)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountTicket indicates an expected call of CountTicket.
func (mr *MockTicketRepositoryMockRecorder) CountTicket(ctx, userId, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountTicket", reflect.TypeOf((*MockTicketRepository)(nil).CountTicket), ctx, userId, status)
}

// CreateBizTicket mocks base method.
func (m *MockTicketRepository) CreateBizTicket(ctx context.Context, ticket domain.Ticket) (domain.Ticket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBizTicket", ctx, ticket)
	ret0, _ := ret[0].(domain.Ticket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBizTicket indicates an expected call of CreateBizTicket.
func (mr *MockTicketRepositoryMockRecorder) CreateBizTicket(ctx, ticket any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBizTicket", reflect.TypeOf((*MockTicketRepository)(nil).CreateBizTicket), ctx, ticket)
}

// CreateTaskForm mocks base method.
func (m *MockTicketRepository) CreateTaskForm(ctx context.Context, taskId int, ticketId int64, fields []domain.FormValue) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTaskForm", ctx, taskId, ticketId, fields)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTaskForm indicates an expected call of CreateTaskForm.
func (mr *MockTicketRepositoryMockRecorder) CreateTaskForm(ctx, taskId, ticketId, fields any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTaskForm", reflect.TypeOf((*MockTicketRepository)(nil).CreateTaskForm), ctx, taskId, ticketId, fields)
}

// CreateTicket mocks base method.
func (m *MockTicketRepository) CreateTicket(ctx context.Context, req domain.Ticket) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTicket", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTicket indicates an expected call of CreateTicket.
func (mr *MockTicketRepositoryMockRecorder) CreateTicket(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTicket", reflect.TypeOf((*MockTicketRepository)(nil).CreateTicket), ctx, req)
}

// Detail mocks base method.
func (m *MockTicketRepository) Detail(ctx context.Context, id int64) (domain.Ticket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Detail", ctx, id)
	ret0, _ := ret[0].(domain.Ticket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Detail indicates an expected call of Detail.
func (mr *MockTicketRepositoryMockRecorder) Detail(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Detail", reflect.TypeOf((*MockTicketRepository)(nil).Detail), ctx, id)
}

// DetailByProcessInstId mocks base method.
func (m *MockTicketRepository) DetailByProcessInstId(ctx context.Context, instanceId int) (domain.Ticket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetailByProcessInstId", ctx, instanceId)
	ret0, _ := ret[0].(domain.Ticket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DetailByProcessInstId indicates an expected call of DetailByProcessInstId.
func (mr *MockTicketRepositoryMockRecorder) DetailByProcessInstId(ctx, instanceId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetailByProcessInstId", reflect.TypeOf((*MockTicketRepository)(nil).DetailByProcessInstId), ctx, instanceId)
}

// FindByBizIdAndKey mocks base method.
func (m *MockTicketRepository) FindByBizIdAndKey(ctx context.Context, bizId int64, key string, status []domain.Status) (domain.Ticket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByBizIdAndKey", ctx, bizId, key, status)
	ret0, _ := ret[0].(domain.Ticket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByBizIdAndKey indicates an expected call of FindByBizIdAndKey.
func (mr *MockTicketRepositoryMockRecorder) FindByBizIdAndKey(ctx, bizId, key, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByBizIdAndKey", reflect.TypeOf((*MockTicketRepository)(nil).FindByBizIdAndKey), ctx, bizId, key, status)
}

// FindTaskFormsBatch mocks base method.
func (m *MockTicketRepository) FindTaskFormsBatch(ctx context.Context, taskIds []int) (map[int][]domain.FormValue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTaskFormsBatch", ctx, taskIds)
	ret0, _ := ret[0].(map[int][]domain.FormValue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTaskFormsBatch indicates an expected call of FindTaskFormsBatch.
func (mr *MockTicketRepositoryMockRecorder) FindTaskFormsBatch(ctx, taskIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTaskFormsBatch", reflect.TypeOf((*MockTicketRepository)(nil).FindTaskFormsBatch), ctx, taskIds)
}

// FindTaskFormsByTicketID mocks base method.
func (m *MockTicketRepository) FindTaskFormsByTicketID(ctx context.Context, ticketID int64) ([]domain.FormValue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTaskFormsByTicketID", ctx, ticketID)
	ret0, _ := ret[0].([]domain.FormValue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTaskFormsByTicketID indicates an expected call of FindTaskFormsByTicketID.
func (mr *MockTicketRepositoryMockRecorder) FindTaskFormsByTicketID(ctx, ticketID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTaskFormsByTicketID", reflect.TypeOf((*MockTicketRepository)(nil).FindTaskFormsByTicketID), ctx, ticketID)
}

// ListHistory mocks base method.
func (m *MockTicketRepository) ListHistory(ctx context.Context, userId string, status []int, offset, limit int64) ([]domain.Ticket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListHistory", ctx, userId, status, offset, limit)
	ret0, _ := ret[0].([]domain.Ticket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListHistory indicates an expected call of ListHistory.
func (mr *MockTicketRepositoryMockRecorder) ListHistory(ctx, userId, status, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListHistory", reflect.TypeOf((*MockTicketRepository)(nil).ListHistory), ctx, userId, status, offset, limit)
}

// ListProcessStartFailed mocks base method.
func (m *MockTicketRepository) ListProcessStartFailed(ctx context.Context, userId string, offset, limit int64) ([]domain.Ticket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProcessStartFailed", ctx, userId, offset, limit)
	ret0, _ := ret[0].([]domain.Ticket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProcessStartFailed indicates an expected call of ListProcessStartFailed.
func (mr *MockTicketRepositoryMockRecorder) ListProcessStartFailed(ctx, userId, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProcessStartFailed", reflect.TypeOf((*MockTicketRepository)(nil).ListProcessStartFailed), ctx, userId, offset, limit)
}

// ListTicket mocks base method.
func (m *MockTicketRepository) ListTicket(ctx context.Context, userId string, status []int, offset, limit int64) ([]domain.Ticket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTicket", ctx, userId, status, offset, limit)
	ret0, _ := ret[0].([]domain.Ticket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTicket indicates an expected call of ListTicket.
func (mr *MockTicketRepositoryMockRecorder) ListTicket(ctx, userId, status, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTicket", reflect.TypeOf((*MockTicketRepository)(nil).ListTicket), ctx, userId, status, offset, limit)
}

// ListTicketByProcessInstanceIds mocks base method.
func (m *MockTicketRepository) ListTicketByProcessInstanceIds(ctx context.Context, instanceIds []int) ([]domain.Ticket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTicketByProcessInstanceIds", ctx, instanceIds)
	ret0, _ := ret[0].([]domain.Ticket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTicketByProcessInstanceIds indicates an expected call of ListTicketByProcessInstanceIds.
func (mr *MockTicketRepositoryMockRecorder) ListTicketByProcessInstanceIds(ctx, instanceIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTicketByProcessInstanceIds", reflect.TypeOf((*MockTicketRepository)(nil).ListTicketByProcessInstanceIds), ctx, instanceIds)
}

// MarkProcessStartFailed mocks base method.
func (m *MockTicketRepository) MarkProcessStartFailed(ctx context.Context, id int64, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkProcessStartFailed", ctx, id, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkProcessStartFailed indicates an expected call of MarkProcessStartFailed.
func (mr *MockTicketRepositoryMockRecorder) MarkProcessStartFailed(ctx, id, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkProcessStartFailed", reflect.TypeOf((*MockTicketRepository)(nil).MarkProcessStartFailed), ctx, id, reason)
}

// MergeTicketData mocks base method.
func (m *MockTicketRepository) MergeTicketData(ctx context.Context, id int64, data map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergeTicketData", ctx, id, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// MergeTicketData indicates an expected call of MergeTicketData.
func (mr *MockTicketRepositoryMockRecorder) MergeTicketData(ctx, id, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergeTicketData", reflect.TypeOf((*MockTicketRepository)(nil).MergeTicketData), ctx, id, data)
}

// PrepareProcessRestart mocks base method.
func (m *MockTicketRepository) PrepareProcessRestart(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrepareProcessRestart", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// PrepareProcessRestart indicates an expected call of PrepareProcessRestart.
func (mr *MockTicketRepositoryMockRecorder) PrepareProcessRestart(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareProcessRestart", reflect.TypeOf((*MockTicketRepository)(nil).PrepareProcessRestart), ctx, id)
}

// RegisterProcessInstanceId mocks base method.
func (m *MockTicketRepository) RegisterProcessInstanceId(ctx context.Context, id int64, instanceId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterProcessInstanceId", ctx, id, instanceId)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterProcessInstanceId indicates an expected call of RegisterProcessInstanceId.
func (mr *MockTicketRepositoryMockRecorder) RegisterProcessInstanceId(ctx, id, instanceId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterProcessInstanceId", reflect.TypeOf((*MockTicketRepository)(nil).RegisterProcessInstanceId), ctx, id, instanceId)
}

// UpdateStatusByInstanceId mocks base method.
func (m *MockTicketRepository) UpdateStatusByInstanceId(ctx context.Context, instanceId int, status uint8) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatusByInstanceId", ctx, instanceId, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatusByInstanceId indicates an expected call of UpdateStatusByInstanceId.
func (mr *MockTicketRepositoryMockRecorder) UpdateStatusByInstanceId(ctx, instanceId, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatusByInstanceId", reflect.TypeOf((*MockTicketRepository)(nil).UpdateStatusByInstanceId), ctx, instanceId, status)
}
