// Code generated by MockGen. DO NOT EDIT.
// Source: ./workflow.go
//
// Generated by this command:
//
//	mockgen -source=./workflow.go -package=repomocks -destination=./mocks/workflow_repo.mock.go -typed IWorkflowRepository
//

// Package repomocks is a generated GoMock package.
package repomocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Duke1616/eflow/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockIWorkflowCoreRepository is a mock of IWorkflowCoreRepository interface.
type MockIWorkflowCoreRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIWorkflowCoreRepositoryMockRecorder
	isgomock struct{}
}

// MockIWorkflowCoreRepositoryMockRecorder is the mock recorder for MockIWorkflowCoreRepository.
type MockIWorkflowCoreRepositoryMockRecorder struct {
	mock *MockIWorkflowCoreRepository
}

// NewMockIWorkflowCoreRepository creates a new mock instance.
func NewMockIWorkflowCoreRepository(ctrl *gomock.Controller) *MockIWorkflowCoreRepository {
	mock := &MockIWorkflowCoreRepository{ctrl: ctrl}
	mock.recorder = &MockIWorkflowCoreRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIWorkflowCoreRepository) EXPECT() *MockIWorkflowCoreRepositoryMockRecorder {
	return m.recorder
}

// CountByKeyword mocks base method.
func (m *MockIWorkflowCoreRepository) CountByKeyword(ctx context.Context, keyword string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByKeyword", ctx, keyword)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByKeyword indicates an expected call of CountByKeyword.
func (mr *MockIWorkflowCoreRepositoryMockRecorder) CountByKeyword(ctx, keyword any) *MockIWorkflowCoreRepositoryCountByKeywordCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByKeyword", reflect.TypeOf((*MockIWorkflowCoreRepository)(nil).CountByKeyword), ctx, keyword)
	return &MockIWorkflowCoreRepositoryCountByKeywordCall{Call: call}
}

// MockIWorkflowCoreRepositoryCountByKeywordCall wrap *gomock.Call
type MockIWorkflowCoreRepositoryCountByKeywordCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIWorkflowCoreRepositoryCountByKeywordCall) Return(arg0 int64, arg1 error) *MockIWorkflowCoreRepositoryCountByKeywordCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIWorkflowCoreRepositoryCountByKeywordCall) Do(f func(context.Context, string) (int64, error)) *MockIWorkflowCoreRepositoryCountByKeywordCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIWorkflowCoreRepositoryCountByKeywordCall) DoAndReturn(f func(context.Context, string) (int64, error)) *MockIWorkflowCoreRepositoryCountByKeywordCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Create mocks base method.
func (m *MockIWorkflowCoreRepository) Create(ctx context.Context, req domain.Workflow) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIWorkflowCoreRepositoryMockRecorder) Create(ctx, req any) *MockIWorkflowCoreRepositoryCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIWorkflowCoreRepository)(nil).Create), ctx, req)
	return &MockIWorkflowCoreRepositoryCreateCall{Call: call}
}

// MockIWorkflowCoreRepositoryCreateCall wrap *gomock.Call
type MockIWorkflowCoreRepositoryCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIWorkflowCoreRepositoryCreateCall) Return(arg0 int64, arg1 error) *MockIWorkflowCoreRepositoryCreateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIWorkflowCoreRepositoryCreateCall) Do(f func(context.Context, domain.Workflow) (int64, error)) *MockIWorkflowCoreRepositoryCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIWorkflowCoreRepositoryCreateCall) DoAndReturn(f func(context.Context, domain.Workflow) (int64, error)) *MockIWorkflowCoreRepositoryCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockIWorkflowCoreRepository) Delete(ctx context.Context, id int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockIWorkflowCoreRepositoryMockRecorder) Delete(ctx, id any) *MockIWorkflowCoreRepositoryDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIWorkflowCoreRepository)(nil).Delete), ctx, id)
	return &MockIWorkflowCoreRepositoryDeleteCall{Call: call}
}

// MockIWorkflowCoreRepositoryDeleteCall wrap *gomock.Call
type MockIWorkflowCoreRepositoryDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIWorkflowCoreRepositoryDeleteCall) Return(arg0 int64, arg1 error) *MockIWorkflowCoreRepositoryDeleteCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIWorkflowCoreRepositoryDeleteCall) Do(f func(context.Context, int64) (int64, error)) *MockIWorkflowCoreRepositoryDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIWorkflowCoreRepositoryDeleteCall) DoAndReturn(f func(context.Context, int64) (int64, error)) *MockIWorkflowCoreRepositoryDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Find mocks base method.
func (m *MockIWorkflowCoreRepository) Find(ctx context.Context, id int64) (domain.Workflow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(domain.Workflow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockIWorkflowCoreRepositoryMockRecorder) Find(ctx, id any) *MockIWorkflowCoreRepositoryFindCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockIWorkflowCoreRepository)(nil).Find), ctx, id)
	return &MockIWorkflowCoreRepositoryFindCall{Call: call}
}

// MockIWorkflowCoreRepositoryFindCall wrap *gomock.Call
type MockIWorkflowCoreRepositoryFindCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIWorkflowCoreRepositoryFindCall) Return(arg0 domain.Workflow, arg1 error) *MockIWorkflowCoreRepositoryFindCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIWorkflowCoreRepositoryFindCall) Do(f func(context.Context, int64) (domain.Workflow, error)) *MockIWorkflowCoreRepositoryFindCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIWorkflowCoreRepositoryFindCall) DoAndReturn(f func(context.Context, int64) (domain.Workflow, error)) *MockIWorkflowCoreRepositoryFindCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindByIds mocks base method.
func (m *MockIWorkflowCoreRepository) FindByIds(ctx context.Context, ids []int64) ([]domain.Workflow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIds", ctx, ids)
	ret0, _ := ret[0].([]domain.Workflow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIds indicates an expected call of FindByIds.
func (mr *MockIWorkflowCoreRepositoryMockRecorder) FindByIds(ctx, ids any) *MockIWorkflowCoreRepositoryFindByIdsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIds", reflect.TypeOf((*MockIWorkflowCoreRepository)(nil).FindByIds), ctx, ids)
	return &MockIWorkflowCoreRepositoryFindByIdsCall{Call: call}
}

// MockIWorkflowCoreRepositoryFindByIdsCall wrap *gomock.Call
type MockIWorkflowCoreRepositoryFindByIdsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIWorkflowCoreRepositoryFindByIdsCall) Return(arg0 []domain.Workflow, arg1 error) *MockIWorkflowCoreRepositoryFindByIdsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIWorkflowCoreRepositoryFindByIdsCall) Do(f func(context.Context, []int64) ([]domain.Workflow, error)) *MockIWorkflowCoreRepositoryFindByIdsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIWorkflowCoreRepositoryFindByIdsCall) DoAndReturn(f func(context.Context, []int64) ([]domain.Workflow, error)) *MockIWorkflowCoreRepositoryFindByIdsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindByKeyword mocks base method.
func (m *MockIWorkflowCoreRepository) FindByKeyword(ctx context.Context, keyword string, offset, limit int64) ([]domain.Workflow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByKeyword", ctx, keyword, offset, limit)
	ret0, _ := ret[0].([]domain.Workflow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByKeyword indicates an expected call of FindByKeyword.
func (mr *MockIWorkflowCoreRepositoryMockRecorder) FindByKeyword(ctx, keyword, offset, limit any) *MockIWorkflowCoreRepositoryFindByKeywordCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByKeyword", reflect.TypeOf((*MockIWorkflowCoreRepository)(nil).FindByKeyword), ctx, keyword, offset, limit)
	return &MockIWorkflowCoreRepositoryFindByKeywordCall{Call: call}
}

// MockIWorkflowCoreRepositoryFindByKeywordCall wrap *gomock.Call
type MockIWorkflowCoreRepositoryFindByKeywordCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIWorkflowCoreRepositoryFindByKeywordCall) Return(arg0 []domain.Workflow, arg1 error) *MockIWorkflowCoreRepositoryFindByKeywordCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIWorkflowCoreRepositoryFindByKeywordCall) Do(f func(context.Context, string, int64, int64) ([]domain.Workflow, error)) *MockIWorkflowCoreRepositoryFindByKeywordCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIWorkflowCoreRepositoryFindByKeywordCall) DoAndReturn(f func(context.Context, string, int64, int64) ([]domain.Workflow, error)) *MockIWorkflowCoreRepositoryFindByKeywordCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockIWorkflowCoreRepository) List(ctx context.Context, offset, limit int64) ([]domain.Workflow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, offset, limit)
	ret0, _ := ret[0].([]domain.Workflow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockIWorkflowCoreRepositoryMockRecorder) List(ctx, offset, limit any) *MockIWorkflowCoreRepositoryListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIWorkflowCoreRepository)(nil).List), ctx, offset, limit)
	return &MockIWorkflowCoreRepositoryListCall{Call: call}
}

// MockIWorkflowCoreRepositoryListCall wrap *gomock.Call
type MockIWorkflowCoreRepositoryListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIWorkflowCoreRepositoryListCall) Return(arg0 []domain.Workflow, arg1 error) *MockIWorkflowCoreRepositoryListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIWorkflowCoreRepositoryListCall) Do(f func(context.Context, int64, int64) ([]domain.Workflow, error)) *MockIWorkflowCoreRepositoryListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIWorkflowCoreRepositoryListCall) DoAndReturn(f func(context.Context, int64, int64) ([]domain.Workflow, error)) *MockIWorkflowCoreRepositoryListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Total mocks base method.
func (m *MockIWorkflowCoreRepository) Total(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Total", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Total indicates an expected call of Total.
func (mr *MockIWorkflowCoreRepositoryMockRecorder) Total(ctx any) *MockIWorkflowCoreRepositoryTotalCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Total", reflect.TypeOf((*MockIWorkflowCoreRepository)(nil).Total), ctx)
	return &MockIWorkflowCoreRepositoryTotalCall{Call: call}
}

// MockIWorkflowCoreRepositoryTotalCall wrap *gomock.Call
type MockIWorkflowCoreRepositoryTotalCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIWorkflowCoreRepositoryTotalCall) Return(arg0 int64, arg1 error) *MockIWorkflowCoreRepositoryTotalCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIWorkflowCoreRepositoryTotalCall) Do(f func(context.Context) (int64, error)) *MockIWorkflowCoreRepositoryTotalCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIWorkflowCoreRepositoryTotalCall) DoAndReturn(f func(context.Context) (int64, error)) *MockIWorkflowCoreRepositoryTotalCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockIWorkflowCoreRepository) Update(ctx context.Context, req domain.Workflow) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockIWorkflowCoreRepositoryMockRecorder) Update(ctx, req any) *MockIWorkflowCoreRepositoryUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIWorkflowCoreRepository)(nil).Update), ctx, req)
	return &MockIWorkflowCoreRepositoryUpdateCall{Call: call}
}

// MockIWorkflowCoreRepositoryUpdateCall wrap *gomock.Call
type MockIWorkflowCoreRepositoryUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIWorkflowCoreRepositoryUpdateCall) Return(arg0 int64, arg1 error) *MockIWorkflowCoreRepositoryUpdateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIWorkflowCoreRepositoryUpdateCall) Do(f func(context.Context, domain.Workflow) (int64, error)) *MockIWorkflowCoreRepositoryUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIWorkflowCoreRepositoryUpdateCall) DoAndReturn(f func(context.Context, domain.Workflow) (int64, error)) *MockIWorkflowCoreRepositoryUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateProcessId mocks base method.
func (m *MockIWorkflowCoreRepository) UpdateProcessId(ctx context.Context, id int64, processId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProcessId", ctx, id, processId)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProcessId indicates an expected call of UpdateProcessId.
func (mr *MockIWorkflowCoreRepositoryMockRecorder) UpdateProcessId(ctx, id, processId any) *MockIWorkflowCoreRepositoryUpdateProcessIdCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProcessId", reflect.TypeOf((*MockIWorkflowCoreRepository)(nil).UpdateProcessId), ctx, id, processId)
	return &MockIWorkflowCoreRepositoryUpdateProcessIdCall{Call: call}
}

// MockIWorkflowCoreRepositoryUpdateProcessIdCall wrap *gomock.Call
type MockIWorkflowCoreRepositoryUpdateProcessIdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIWorkflowCoreRepositoryUpdateProcessIdCall) Return(arg0 error) *MockIWorkflowCoreRepositoryUpdateProcessIdCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIWorkflowCoreRepositoryUpdateProcessIdCall) Do(f func(context.Context, int64, int) error) *MockIWorkflowCoreRepositoryUpdateProcessIdCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIWorkflowCoreRepositoryUpdateProcessIdCall) DoAndReturn(f func(context.Context, int64, int) error) *MockIWorkflowCoreRepositoryUpdateProcessIdCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockISnapshotRepository is a mock of ISnapshotRepository interface.
type MockISnapshotRepository struct {
	ctrl     *gomock.Controller
	recorder *MockISnapshotRepositoryMockRecorder
	isgomock struct{}
}

// MockISnapshotRepositoryMockRecorder is the mock recorder for MockISnapshotRepository.
type MockISnapshotRepositoryMockRecorder struct {
	mock *MockISnapshotRepository
}

// NewMockISnapshotRepository creates a new mock instance.
func NewMockISnapshotRepository(ctrl *gomock.Controller) *MockISnapshotRepository {
	mock := &MockISnapshotRepository{ctrl: ctrl}
	mock.recorder = &MockISnapshotRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISnapshotRepository) EXPECT() *MockISnapshotRepositoryMockRecorder {
	return m.recorder
}

// CreateSnapshot mocks base method.
func (m *MockISnapshotRepository) CreateSnapshot(ctx context.Context, workflow domain.Workflow, processID, processVersion int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSnapshot", ctx, workflow, processID, processVersion)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSnapshot indicates an expected call of CreateSnapshot.
func (mr *MockISnapshotRepositoryMockRecorder) CreateSnapshot(ctx, workflow, processID, processVersion any) *MockISnapshotRepositoryCreateSnapshotCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSnapshot", reflect.TypeOf((*MockISnapshotRepository)(nil).CreateSnapshot), ctx, workflow, processID, processVersion)
	return &MockISnapshotRepositoryCreateSnapshotCall{Call: call}
}

// MockISnapshotRepositoryCreateSnapshotCall wrap *gomock.Call
type MockISnapshotRepositoryCreateSnapshotCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockISnapshotRepositoryCreateSnapshotCall) Return(arg0 error) *MockISnapshotRepositoryCreateSnapshotCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockISnapshotRepositoryCreateSnapshotCall) Do(f func(context.Context, domain.Workflow, int, int) error) *MockISnapshotRepositoryCreateSnapshotCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockISnapshotRepositoryCreateSnapshotCall) DoAndReturn(f func(context.Context, domain.Workflow, int, int) error) *MockISnapshotRepositoryCreateSnapshotCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindSnapshot mocks base method.
func (m *MockISnapshotRepository) FindSnapshot(ctx context.Context, processID, processVersion int) (domain.Workflow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSnapshot", ctx, processID, processVersion)
	ret0, _ := ret[0].(domain.Workflow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSnapshot indicates an expected call of FindSnapshot.
func (mr *MockISnapshotRepositoryMockRecorder) FindSnapshot(ctx, processID, processVersion any) *MockISnapshotRepositoryFindSnapshotCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSnapshot", reflect.TypeOf((*MockISnapshotRepository)(nil).FindSnapshot), ctx, processID, processVersion)
	return &MockISnapshotRepositoryFindSnapshotCall{Call: call}
}

// MockISnapshotRepositoryFindSnapshotCall wrap *gomock.Call
type MockISnapshotRepositoryFindSnapshotCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockISnapshotRepositoryFindSnapshotCall) Return(arg0 domain.Workflow, arg1 error) *MockISnapshotRepositoryFindSnapshotCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockISnapshotRepositoryFindSnapshotCall) Do(f func(context.Context, int, int) (domain.Workflow, error)) *MockISnapshotRepositoryFindSnapshotCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockISnapshotRepositoryFindSnapshotCall) DoAndReturn(f func(context.Context, int, int) (domain.Workflow, error)) *MockISnapshotRepositoryFindSnapshotCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockIWorkflowRepository is a mock of IWorkflowRepository interface.
type MockIWorkflowRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIWorkflowRepositoryMockRecorder
	isgomock struct{}
}

// MockIWorkflowRepositoryMockRecorder is the mock recorder for MockIWorkflowRepository.
type MockIWorkflowRepositoryMockRecorder struct {
	mock *MockIWorkflowRepository
}

// NewMockIWorkflowRepository creates a new mock instance.
func NewMockIWorkflowRepository(ctrl *gomock.Controller) *MockIWorkflowRepository {
	mock := &MockIWorkflowRepository{ctrl: ctrl}
	mock.recorder = &MockIWorkflowRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIWorkflowRepository) EXPECT() *MockIWorkflowRepositoryMockRecorder {
	return m.recorder
}

// CountByKeyword mocks base method.
func (m *MockIWorkflowRepository) CountByKeyword(ctx context.Context, keyword string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByKeyword", ctx, keyword)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByKeyword indicates an expected call of CountByKeyword.
func (mr *MockIWorkflowRepositoryMockRecorder) CountByKeyword(ctx, keyword any) *MockIWorkflowRepositoryCountByKeywordCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByKeyword", reflect.TypeOf((*MockIWorkflowRepository)(nil).CountByKeyword), ctx, keyword)
	return &MockIWorkflowRepositoryCountByKeywordCall{Call: call}
}

// MockIWorkflowRepositoryCountByKeywordCall wrap *gomock.Call
type MockIWorkflowRepositoryCountByKeywordCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIWorkflowRepositoryCountByKeywordCall) Return(arg0 int64, arg1 error) *MockIWorkflowRepositoryCountByKeywordCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIWorkflowRepositoryCountByKeywordCall) Do(f func(context.Context, string) (int64, error)) *MockIWorkflowRepositoryCountByKeywordCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIWorkflowRepositoryCountByKeywordCall) DoAndReturn(f func(context.Context, string) (int64, error)) *MockIWorkflowRepositoryCountByKeywordCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Create mocks base method.
func (m *MockIWorkflowRepository) Create(ctx context.Context, req domain.Workflow) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIWorkflowRepositoryMockRecorder) Create(ctx, req any) *MockIWorkflowRepositoryCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIWorkflowRepository)(nil).Create), ctx, req)
	return &MockIWorkflowRepositoryCreateCall{Call: call}
}

// MockIWorkflowRepositoryCreateCall wrap *gomock.Call
type MockIWorkflowRepositoryCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIWorkflowRepositoryCreateCall) Return(arg0 int64, arg1 error) *MockIWorkflowRepositoryCreateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIWorkflowRepositoryCreateCall) Do(f func(context.Context, domain.Workflow) (int64, error)) *MockIWorkflowRepositoryCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIWorkflowRepositoryCreateCall) DoAndReturn(f func(context.Context, domain.Workflow) (int64, error)) *MockIWorkflowRepositoryCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateSnapshot mocks base method.
func (m *MockIWorkflowRepository) CreateSnapshot(ctx context.Context, workflow domain.Workflow, processID, processVersion int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSnapshot", ctx, workflow, processID, processVersion)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSnapshot indicates an expected call of CreateSnapshot.
func (mr *MockIWorkflowRepositoryMockRecorder) CreateSnapshot(ctx, workflow, processID, processVersion any) *MockIWorkflowRepositoryCreateSnapshotCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSnapshot", reflect.TypeOf((*MockIWorkflowRepository)(nil).CreateSnapshot), ctx, workflow, processID, processVersion)
	return &MockIWorkflowRepositoryCreateSnapshotCall{Call: call}
}

// MockIWorkflowRepositoryCreateSnapshotCall wrap *gomock.Call
type MockIWorkflowRepositoryCreateSnapshotCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIWorkflowRepositoryCreateSnapshotCall) Return(arg0 error) *MockIWorkflowRepositoryCreateSnapshotCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIWorkflowRepositoryCreateSnapshotCall) Do(f func(context.Context, domain.Workflow, int, int) error) *MockIWorkflowRepositoryCreateSnapshotCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIWorkflowRepositoryCreateSnapshotCall) DoAndReturn(f func(context.Context, domain.Workflow, int, int) error) *MockIWorkflowRepositoryCreateSnapshotCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockIWorkflowRepository) Delete(ctx context.Context, id int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockIWorkflowRepositoryMockRecorder) Delete(ctx, id any) *MockIWorkflowRepositoryDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIWorkflowRepository)(nil).Delete), ctx, id)
	return &MockIWorkflowRepositoryDeleteCall{Call: call}
}

// MockIWorkflowRepositoryDeleteCall wrap *gomock.Call
type MockIWorkflowRepositoryDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIWorkflowRepositoryDeleteCall) Return(arg0 int64, arg1 error) *MockIWorkflowRepositoryDeleteCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIWorkflowRepositoryDeleteCall) Do(f func(context.Context, int64) (int64, error)) *MockIWorkflowRepositoryDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIWorkflowRepositoryDeleteCall) DoAndReturn(f func(context.Context, int64) (int64, error)) *MockIWorkflowRepositoryDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Find mocks base method.
func (m *MockIWorkflowRepository) Find(ctx context.Context, id int64) (domain.Workflow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(domain.Workflow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockIWorkflowRepositoryMockRecorder) Find(ctx, id any) *MockIWorkflowRepositoryFindCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockIWorkflowRepository)(nil).Find), ctx, id)
	return &MockIWorkflowRepositoryFindCall{Call: call}
}

// MockIWorkflowRepositoryFindCall wrap *gomock.Call
type MockIWorkflowRepositoryFindCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIWorkflowRepositoryFindCall) Return(arg0 domain.Workflow, arg1 error) *MockIWorkflowRepositoryFindCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIWorkflowRepositoryFindCall) Do(f func(context.Context, int64) (domain.Workflow, error)) *MockIWorkflowRepositoryFindCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIWorkflowRepositoryFindCall) DoAndReturn(f func(context.Context, int64) (domain.Workflow, error)) *MockIWorkflowRepositoryFindCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindByIds mocks base method.
func (m *MockIWorkflowRepository) FindByIds(ctx context.Context, ids []int64) ([]domain.Workflow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIds", ctx, ids)
	ret0, _ := ret[0].([]domain.Workflow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIds indicates an expected call of FindByIds.
func (mr *MockIWorkflowRepositoryMockRecorder) FindByIds(ctx, ids any) *MockIWorkflowRepositoryFindByIdsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIds", reflect.TypeOf((*MockIWorkflowRepository)(nil).FindByIds), ctx, ids)
	return &MockIWorkflowRepositoryFindByIdsCall{Call: call}
}

// MockIWorkflowRepositoryFindByIdsCall wrap *gomock.Call
type MockIWorkflowRepositoryFindByIdsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIWorkflowRepositoryFindByIdsCall) Return(arg0 []domain.Workflow, arg1 error) *MockIWorkflowRepositoryFindByIdsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIWorkflowRepositoryFindByIdsCall) Do(f func(context.Context, []int64) ([]domain.Workflow, error)) *MockIWorkflowRepositoryFindByIdsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIWorkflowRepositoryFindByIdsCall) DoAndReturn(f func(context.Context, []int64) ([]domain.Workflow, error)) *MockIWorkflowRepositoryFindByIdsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindByKeyword mocks base method.
func (m *MockIWorkflowRepository) FindByKeyword(ctx context.Context, keyword string, offset, limit int64) ([]domain.Workflow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByKeyword", ctx, keyword, offset, limit)
	ret0, _ := ret[0].([]domain.Workflow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByKeyword indicates an expected call of FindByKeyword.
func (mr *MockIWorkflowRepositoryMockRecorder) FindByKeyword(ctx, keyword, offset, limit any) *MockIWorkflowRepositoryFindByKeywordCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByKeyword", reflect.TypeOf((*MockIWorkflowRepository)(nil).FindByKeyword), ctx, keyword, offset, limit)
	return &MockIWorkflowRepositoryFindByKeywordCall{Call: call}
}

// MockIWorkflowRepositoryFindByKeywordCall wrap *gomock.Call
type MockIWorkflowRepositoryFindByKeywordCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIWorkflowRepositoryFindByKeywordCall) Return(arg0 []domain.Workflow, arg1 error) *MockIWorkflowRepositoryFindByKeywordCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIWorkflowRepositoryFindByKeywordCall) Do(f func(context.Context, string, int64, int64) ([]domain.Workflow, error)) *MockIWorkflowRepositoryFindByKeywordCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIWorkflowRepositoryFindByKeywordCall) DoAndReturn(f func(context.Context, string, int64, int64) ([]domain.Workflow, error)) *MockIWorkflowRepositoryFindByKeywordCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindSnapshot mocks base method.
func (m *MockIWorkflowRepository) FindSnapshot(ctx context.Context, processID, processVersion int) (domain.Workflow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSnapshot", ctx, processID, processVersion)
	ret0, _ := ret[0].(domain.Workflow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSnapshot indicates an expected call of FindSnapshot.
func (mr *MockIWorkflowRepositoryMockRecorder) FindSnapshot(ctx, processID, processVersion any) *MockIWorkflowRepositoryFindSnapshotCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSnapshot", reflect.TypeOf((*MockIWorkflowRepository)(nil).FindSnapshot), ctx, processID, processVersion)
	return &MockIWorkflowRepositoryFindSnapshotCall{Call: call}
}

// MockIWorkflowRepositoryFindSnapshotCall wrap *gomock.Call
type MockIWorkflowRepositoryFindSnapshotCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIWorkflowRepositoryFindSnapshotCall) Return(arg0 domain.Workflow, arg1 error) *MockIWorkflowRepositoryFindSnapshotCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIWorkflowRepositoryFindSnapshotCall) Do(f func(context.Context, int, int) (domain.Workflow, error)) *MockIWorkflowRepositoryFindSnapshotCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIWorkflowRepositoryFindSnapshotCall) DoAndReturn(f func(context.Context, int, int) (domain.Workflow, error)) *MockIWorkflowRepositoryFindSnapshotCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockIWorkflowRepository) List(ctx context.Context, offset, limit int64) ([]domain.Workflow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, offset, limit)
	ret0, _ := ret[0].([]domain.Workflow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockIWorkflowRepositoryMockRecorder) List(ctx, offset, limit any) *MockIWorkflowRepositoryListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIWorkflowRepository)(nil).List), ctx, offset, limit)
	return &MockIWorkflowRepositoryListCall{Call: call}
}

// MockIWorkflowRepositoryListCall wrap *gomock.Call
type MockIWorkflowRepositoryListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIWorkflowRepositoryListCall) Return(arg0 []domain.Workflow, arg1 error) *MockIWorkflowRepositoryListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIWorkflowRepositoryListCall) Do(f func(context.Context, int64, int64) ([]domain.Workflow, error)) *MockIWorkflowRepositoryListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIWorkflowRepositoryListCall) DoAndReturn(f func(context.Context, int64, int64) ([]domain.Workflow, error)) *MockIWorkflowRepositoryListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Total mocks base method.
func (m *MockIWorkflowRepository) Total(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Total", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Total indicates an expected call of Total.
func (mr *MockIWorkflowRepositoryMockRecorder) Total(ctx any) *MockIWorkflowRepositoryTotalCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Total", reflect.TypeOf((*MockIWorkflowRepository)(nil).Total), ctx)
	return &MockIWorkflowRepositoryTotalCall{Call: call}
}

// MockIWorkflowRepositoryTotalCall wrap *gomock.Call
type MockIWorkflowRepositoryTotalCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIWorkflowRepositoryTotalCall) Return(arg0 int64, arg1 error) *MockIWorkflowRepositoryTotalCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIWorkflowRepositoryTotalCall) Do(f func(context.Context) (int64, error)) *MockIWorkflowRepositoryTotalCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIWorkflowRepositoryTotalCall) DoAndReturn(f func(context.Context) (int64, error)) *MockIWorkflowRepositoryTotalCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockIWorkflowRepository) Update(ctx context.Context, req domain.Workflow) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockIWorkflowRepositoryMockRecorder) Update(ctx, req any) *MockIWorkflowRepositoryUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIWorkflowRepository)(nil).Update), ctx, req)
	return &MockIWorkflowRepositoryUpdateCall{Call: call}
}

// MockIWorkflowRepositoryUpdateCall wrap *gomock.Call
type MockIWorkflowRepositoryUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIWorkflowRepositoryUpdateCall) Return(arg0 int64, arg1 error) *MockIWorkflowRepositoryUpdateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIWorkflowRepositoryUpdateCall) Do(f func(context.Context, domain.Workflow) (int64, error)) *MockIWorkflowRepositoryUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIWorkflowRepositoryUpdateCall) DoAndReturn(f func(context.Context, domain.Workflow) (int64, error)) *MockIWorkflowRepositoryUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateProcessId mocks base method.
func (m *MockIWorkflowRepository) UpdateProcessId(ctx context.Context, id int64, processId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProcessId", ctx, id, processId)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProcessId indicates an expected call of UpdateProcessId.
func (mr *MockIWorkflowRepositoryMockRecorder) UpdateProcessId(ctx, id, processId any) *MockIWorkflowRepositoryUpdateProcessIdCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProcessId", reflect.TypeOf((*MockIWorkflowRepository)(nil).UpdateProcessId), ctx, id, processId)
	return &MockIWorkflowRepositoryUpdateProcessIdCall{Call: call}
}

// MockIWorkflowRepositoryUpdateProcessIdCall wrap *gomock.Call
type MockIWorkflowRepositoryUpdateProcessIdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIWorkflowRepositoryUpdateProcessIdCall) Return(arg0 error) *MockIWorkflowRepositoryUpdateProcessIdCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIWorkflowRepositoryUpdateProcessIdCall) Do(f func(context.Context, int64, int) error) *MockIWorkflowRepositoryUpdateProcessIdCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIWorkflowRepositoryUpdateProcessIdCall) DoAndReturn(f func(context.Context, int64, int) error) *MockIWorkflowRepositoryUpdateProcessIdCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
