// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/Duke1616/eflow/internal/repository"
	"github.com/Duke1616/eflow/internal/repository/dao"
	"github.com/Duke1616/eflow/internal/service"
	"github.com/Duke1616/eflow/internal/web/template"
	"github.com/Duke1616/eflow/internal/web/workflow"
	"github.com/Duke1616/eflow/pkg/easyflow"
)

// Injectors from wire.go:

// InitApp 初始化完整应用
func InitApp() *App {
	v := InitGinMiddlewares()
	sdk := InitPolicySDK()
	syncer := InitPermSyncer()
	v2 := InitProviders()
	db := InitDB()
	iTemplateDAO := dao.NewTemplateDAO(db)
	iTemplateRepository := repository.NewTemplateRepository(iTemplateDAO)
	workwxApp := InitWorkWx()
	iTemplate := service.NewTemplateService(iTemplateRepository, workwxApp)
	handler := template.NewHandler(iTemplate)
	iWorkflowDAO := dao.NewWorkflowDAO(db)
	iWorkflowRepository := repository.NewWorkflowRepository(iWorkflowDAO)
	iEngineDAO := dao.NewProcessEngineDAO(db)
	iEngineRepository := repository.NewProcessEngineRepository(iEngineDAO)
	iEngine := service.NewEngineService(iEngineRepository)
	converter := easyflow.NewLogicFlowToEngineConvert()
	iWorkflow := service.NewWorkflowService(iWorkflowRepository, iEngine, converter)
	workflowHandler := workflow.NewHandler(iWorkflow, iEngine)
	listener := InitListener()
	component := InitGinWebServer(v, sdk, syncer, v2, handler, workflowHandler, listener)
	clientConnInterface := InitECMDBGrpcClient()
	endpointServiceClient := InitEndpointServiceClient(clientConnInterface)
	v3 := InitTasks()
	app := &App{
		Web:         component,
		EndpointSvc: endpointServiceClient,
		Tasks:       v3,
	}
	return app
}
