// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/Duke1616/eflow/internal/repository"
	"github.com/Duke1616/eflow/internal/repository/dao"
	"github.com/Duke1616/eflow/internal/service/codebook"
	"github.com/Duke1616/eflow/internal/service/engine"
	"github.com/Duke1616/eflow/internal/service/runner"
	"github.com/Duke1616/eflow/internal/service/task"
	"github.com/Duke1616/eflow/internal/service/template"
	"github.com/Duke1616/eflow/internal/service/workflow"
	codebook2 "github.com/Duke1616/eflow/internal/web/codebook"
	runner2 "github.com/Duke1616/eflow/internal/web/runner"
	task2 "github.com/Duke1616/eflow/internal/web/task"
	template2 "github.com/Duke1616/eflow/internal/web/template"
	workflow2 "github.com/Duke1616/eflow/internal/web/workflow"
	"github.com/Duke1616/eflow/pkg/easyflow"
)

// Injectors from wire.go:

// InitApp 初始化完整应用
func InitApp() *App {
	v := InitGinMiddlewares()
	sdk := InitPolicySDK()
	syncer := InitPermSyncer()
	v2 := InitProviders()
	db := InitDB()
	iTemplateDAO := dao.NewTemplateDAO(db)
	iTemplateRepository := repository.NewTemplateRepository(iTemplateDAO)
	workwxApp := InitWorkWx()
	iTemplate := template.NewTemplateService(iTemplateRepository, workwxApp)
	handler := template2.NewHandler(iTemplate)
	iWorkflowDAO := dao.NewWorkflowDAO(db)
	iWorkflowRepository := repository.NewWorkflowRepository(iWorkflowDAO)
	iEngineDAO := dao.NewProcessEngineDAO(db)
	iEngineRepository := repository.NewProcessEngineRepository(iEngineDAO)
	iEngine := engine.NewEngineService(iEngineRepository)
	converter := easyflow.NewLogicFlowToEngineConvert()
	iWorkflow := workflow.NewWorkflowService(iWorkflowRepository, iEngine, converter)
	workflowHandler := workflow2.NewHandler(iWorkflow, iEngine)
	codebookDAO := dao.NewCodebookDAO(db)
	codebookRepository := repository.NewCodebookRepository(codebookDAO)
	codebookCodebook := codebook.NewService(codebookRepository)
	codebookHandler := codebook2.NewHandler(codebookCodebook)
	iRunnerDAO := dao.NewRunnerDAO(db)
	iRunnerRepository := repository.NewRunnerRepository(iRunnerDAO)
	iRunner := runner.NewRunnerService(iRunnerRepository)
	runnerHandler := runner2.NewHandler(iRunner)
	taskDAO := dao.NewTaskDAO(db)
	taskRepository := repository.NewTaskRepository(taskDAO)
	clientConnInterface := InitECMDBGrpcClient()
	taskServiceClient := InitTaskServiceClient(clientConnInterface)
	taskTask := task.NewTaskService(taskRepository, iWorkflow, codebookCodebook, iRunner, iEngine, taskServiceClient)
	taskHandler := task2.NewHandler(taskTask)
	listener := InitListener()
	component := InitGinWebServer(v, sdk, syncer, v2, handler, workflowHandler, codebookHandler, runnerHandler, taskHandler, listener)
	endpointServiceClient := InitEndpointServiceClient(clientConnInterface)
	mq := InitMQ()
	v3 := InitTasks(taskTask, mq)
	app := &App{
		Web:         component,
		EndpointSvc: endpointServiceClient,
		Tasks:       v3,
	}
	return app
}
