// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/service/workflow/workflow.go
//
// Generated by this command:
//
//	mockgen -source=./internal/service/workflow/workflow.go -package=workflowmocks -destination=./internal/service/workflow/mocks/workflow_svc.mock.go Service
//

// Package workflowmocks is a generated GoMock package.
package workflowmocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Duke1616/eflow/internal/domain"
	easyflow "github.com/Duke1616/eflow/internal/pkg/easyflow"
	gomock "go.uber.org/mock/gomock"
)

// MockIWorkflowCoreService is a mock of IWorkflowCoreService interface.
type MockIWorkflowCoreService struct {
	ctrl     *gomock.Controller
	recorder *MockIWorkflowCoreServiceMockRecorder
	isgomock struct{}
}

// MockIWorkflowCoreServiceMockRecorder is the mock recorder for MockIWorkflowCoreService.
type MockIWorkflowCoreServiceMockRecorder struct {
	mock *MockIWorkflowCoreService
}

// NewMockIWorkflowCoreService creates a new mock instance.
func NewMockIWorkflowCoreService(ctrl *gomock.Controller) *MockIWorkflowCoreService {
	mock := &MockIWorkflowCoreService{ctrl: ctrl}
	mock.recorder = &MockIWorkflowCoreServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIWorkflowCoreService) EXPECT() *MockIWorkflowCoreServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIWorkflowCoreService) Create(ctx context.Context, req domain.Workflow) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIWorkflowCoreServiceMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIWorkflowCoreService)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockIWorkflowCoreService) Delete(ctx context.Context, id int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockIWorkflowCoreServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIWorkflowCoreService)(nil).Delete), ctx, id)
}

// Deploy mocks base method.
func (m *MockIWorkflowCoreService) Deploy(ctx context.Context, flow domain.Workflow) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deploy", ctx, flow)
	ret0, _ := ret[0].(error)
	return ret0
}

// Deploy indicates an expected call of Deploy.
func (mr *MockIWorkflowCoreServiceMockRecorder) Deploy(ctx, flow any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deploy", reflect.TypeOf((*MockIWorkflowCoreService)(nil).Deploy), ctx, flow)
}

// Find mocks base method.
func (m *MockIWorkflowCoreService) Find(ctx context.Context, id int64) (domain.Workflow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(domain.Workflow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockIWorkflowCoreServiceMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockIWorkflowCoreService)(nil).Find), ctx, id)
}

// FindByIds mocks base method.
func (m *MockIWorkflowCoreService) FindByIds(ctx context.Context, ids []int64) ([]domain.Workflow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIds", ctx, ids)
	ret0, _ := ret[0].([]domain.Workflow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIds indicates an expected call of FindByIds.
func (mr *MockIWorkflowCoreServiceMockRecorder) FindByIds(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIds", reflect.TypeOf((*MockIWorkflowCoreService)(nil).FindByIds), ctx, ids)
}

// FindByKeyword mocks base method.
func (m *MockIWorkflowCoreService) FindByKeyword(ctx context.Context, keyword string, offset, limit int64) ([]domain.Workflow, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByKeyword", ctx, keyword, offset, limit)
	ret0, _ := ret[0].([]domain.Workflow)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindByKeyword indicates an expected call of FindByKeyword.
func (mr *MockIWorkflowCoreServiceMockRecorder) FindByKeyword(ctx, keyword, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByKeyword", reflect.TypeOf((*MockIWorkflowCoreService)(nil).FindByKeyword), ctx, keyword, offset, limit)
}

// FindInstanceFlow mocks base method.
func (m *MockIWorkflowCoreService) FindInstanceFlow(ctx context.Context, workflowID int64, processID, version int) (domain.Workflow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindInstanceFlow", ctx, workflowID, processID, version)
	ret0, _ := ret[0].(domain.Workflow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindInstanceFlow indicates an expected call of FindInstanceFlow.
func (mr *MockIWorkflowCoreServiceMockRecorder) FindInstanceFlow(ctx, workflowID, processID, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindInstanceFlow", reflect.TypeOf((*MockIWorkflowCoreService)(nil).FindInstanceFlow), ctx, workflowID, processID, version)
}

// GetAutomationNodes mocks base method.
func (m *MockIWorkflowCoreService) GetAutomationNodes(ctx context.Context, workflowId int64) ([]easyflow.AutomationNodeRef, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAutomationNodes", ctx, workflowId)
	ret0, _ := ret[0].([]easyflow.AutomationNodeRef)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAutomationNodes indicates an expected call of GetAutomationNodes.
func (mr *MockIWorkflowCoreServiceMockRecorder) GetAutomationNodes(ctx, workflowId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAutomationNodes", reflect.TypeOf((*MockIWorkflowCoreService)(nil).GetAutomationNodes), ctx, workflowId)
}

// GetAutomationProperty mocks base method.
func (m *MockIWorkflowCoreService) GetAutomationProperty(workflow easyflow.Workflow, nodeId string) (easyflow.AutomationProperty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAutomationProperty", workflow, nodeId)
	ret0, _ := ret[0].(easyflow.AutomationProperty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAutomationProperty indicates an expected call of GetAutomationProperty.
func (mr *MockIWorkflowCoreServiceMockRecorder) GetAutomationProperty(workflow, nodeId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAutomationProperty", reflect.TypeOf((*MockIWorkflowCoreService)(nil).GetAutomationProperty), workflow, nodeId)
}

// GetHighlightedGraph mocks base method.
func (m *MockIWorkflowCoreService) GetHighlightedGraph(ctx context.Context, workflowId int64, processInstanceId int, status domain.Status) (domain.Workflow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHighlightedGraph", ctx, workflowId, processInstanceId, status)
	ret0, _ := ret[0].(domain.Workflow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHighlightedGraph indicates an expected call of GetHighlightedGraph.
func (mr *MockIWorkflowCoreServiceMockRecorder) GetHighlightedGraph(ctx, workflowId, processInstanceId, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHighlightedGraph", reflect.TypeOf((*MockIWorkflowCoreService)(nil).GetHighlightedGraph), ctx, workflowId, processInstanceId, status)
}

// GetWorkflowSnapshot mocks base method.
func (m *MockIWorkflowCoreService) GetWorkflowSnapshot(ctx context.Context, processID, version int) (domain.Workflow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkflowSnapshot", ctx, processID, version)
	ret0, _ := ret[0].(domain.Workflow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkflowSnapshot indicates an expected call of GetWorkflowSnapshot.
func (mr *MockIWorkflowCoreServiceMockRecorder) GetWorkflowSnapshot(ctx, processID, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkflowSnapshot", reflect.TypeOf((*MockIWorkflowCoreService)(nil).GetWorkflowSnapshot), ctx, processID, version)
}

// List mocks base method.
func (m *MockIWorkflowCoreService) List(ctx context.Context, offset, limit int64) ([]domain.Workflow, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, offset, limit)
	ret0, _ := ret[0].([]domain.Workflow)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockIWorkflowCoreServiceMockRecorder) List(ctx, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIWorkflowCoreService)(nil).List), ctx, offset, limit)
}

// Update mocks base method.
func (m *MockIWorkflowCoreService) Update(ctx context.Context, req domain.Workflow) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockIWorkflowCoreServiceMockRecorder) Update(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIWorkflowCoreService)(nil).Update), ctx, req)
}

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockService) Create(ctx context.Context, req domain.Workflow) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockServiceMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockService)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockService) Delete(ctx context.Context, id int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockService)(nil).Delete), ctx, id)
}

// Deploy mocks base method.
func (m *MockService) Deploy(ctx context.Context, flow domain.Workflow) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deploy", ctx, flow)
	ret0, _ := ret[0].(error)
	return ret0
}

// Deploy indicates an expected call of Deploy.
func (mr *MockServiceMockRecorder) Deploy(ctx, flow any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deploy", reflect.TypeOf((*MockService)(nil).Deploy), ctx, flow)
}

// Find mocks base method.
func (m *MockService) Find(ctx context.Context, id int64) (domain.Workflow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(domain.Workflow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockServiceMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockService)(nil).Find), ctx, id)
}

// FindByIds mocks base method.
func (m *MockService) FindByIds(ctx context.Context, ids []int64) ([]domain.Workflow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIds", ctx, ids)
	ret0, _ := ret[0].([]domain.Workflow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIds indicates an expected call of FindByIds.
func (mr *MockServiceMockRecorder) FindByIds(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIds", reflect.TypeOf((*MockService)(nil).FindByIds), ctx, ids)
}

// FindByKeyword mocks base method.
func (m *MockService) FindByKeyword(ctx context.Context, keyword string, offset, limit int64) ([]domain.Workflow, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByKeyword", ctx, keyword, offset, limit)
	ret0, _ := ret[0].([]domain.Workflow)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindByKeyword indicates an expected call of FindByKeyword.
func (mr *MockServiceMockRecorder) FindByKeyword(ctx, keyword, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByKeyword", reflect.TypeOf((*MockService)(nil).FindByKeyword), ctx, keyword, offset, limit)
}

// FindInstanceFlow mocks base method.
func (m *MockService) FindInstanceFlow(ctx context.Context, workflowID int64, processID, version int) (domain.Workflow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindInstanceFlow", ctx, workflowID, processID, version)
	ret0, _ := ret[0].(domain.Workflow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindInstanceFlow indicates an expected call of FindInstanceFlow.
func (mr *MockServiceMockRecorder) FindInstanceFlow(ctx, workflowID, processID, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindInstanceFlow", reflect.TypeOf((*MockService)(nil).FindInstanceFlow), ctx, workflowID, processID, version)
}

// GetAutomationNodes mocks base method.
func (m *MockService) GetAutomationNodes(ctx context.Context, workflowId int64) ([]easyflow.AutomationNodeRef, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAutomationNodes", ctx, workflowId)
	ret0, _ := ret[0].([]easyflow.AutomationNodeRef)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAutomationNodes indicates an expected call of GetAutomationNodes.
func (mr *MockServiceMockRecorder) GetAutomationNodes(ctx, workflowId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAutomationNodes", reflect.TypeOf((*MockService)(nil).GetAutomationNodes), ctx, workflowId)
}

// GetAutomationProperty mocks base method.
func (m *MockService) GetAutomationProperty(workflow easyflow.Workflow, nodeId string) (easyflow.AutomationProperty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAutomationProperty", workflow, nodeId)
	ret0, _ := ret[0].(easyflow.AutomationProperty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAutomationProperty indicates an expected call of GetAutomationProperty.
func (mr *MockServiceMockRecorder) GetAutomationProperty(workflow, nodeId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAutomationProperty", reflect.TypeOf((*MockService)(nil).GetAutomationProperty), workflow, nodeId)
}

// GetHighlightedGraph mocks base method.
func (m *MockService) GetHighlightedGraph(ctx context.Context, workflowId int64, processInstanceId int, status domain.Status) (domain.Workflow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHighlightedGraph", ctx, workflowId, processInstanceId, status)
	ret0, _ := ret[0].(domain.Workflow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHighlightedGraph indicates an expected call of GetHighlightedGraph.
func (mr *MockServiceMockRecorder) GetHighlightedGraph(ctx, workflowId, processInstanceId, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHighlightedGraph", reflect.TypeOf((*MockService)(nil).GetHighlightedGraph), ctx, workflowId, processInstanceId, status)
}

// GetWorkflowSnapshot mocks base method.
func (m *MockService) GetWorkflowSnapshot(ctx context.Context, processID, version int) (domain.Workflow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkflowSnapshot", ctx, processID, version)
	ret0, _ := ret[0].(domain.Workflow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkflowSnapshot indicates an expected call of GetWorkflowSnapshot.
func (mr *MockServiceMockRecorder) GetWorkflowSnapshot(ctx, processID, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkflowSnapshot", reflect.TypeOf((*MockService)(nil).GetWorkflowSnapshot), ctx, processID, version)
}

// List mocks base method.
func (m *MockService) List(ctx context.Context, offset, limit int64) ([]domain.Workflow, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, offset, limit)
	ret0, _ := ret[0].([]domain.Workflow)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockServiceMockRecorder) List(ctx, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockService)(nil).List), ctx, offset, limit)
}

// Update mocks base method.
func (m *MockService) Update(ctx context.Context, req domain.Workflow) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockServiceMockRecorder) Update(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockService)(nil).Update), ctx, req)
}
