// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/service/engine/engine.go
//
// Generated by this command:
//
//	mockgen -source=./internal/service/engine/engine.go -package=enginemocks -destination=./internal/service/engine/mocks/engine_svc.mock.go Service
//

// Package enginemocks is a generated GoMock package.
package enginemocks

import (
	context "context"
	reflect "reflect"

	model "github.com/Bunny3th/easy-workflow/workflow/model"
	domain "github.com/Duke1616/eflow/internal/domain"
	engine "github.com/Duke1616/eflow/internal/service/engine"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AccessibleTaskRecord mocks base method.
func (m *MockService) AccessibleTaskRecord(ctx context.Context, processInstId, offset, limit int) ([]model.Task, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccessibleTaskRecord", ctx, processInstId, offset, limit)
	ret0, _ := ret[0].([]model.Task)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AccessibleTaskRecord indicates an expected call of AccessibleTaskRecord.
func (mr *MockServiceMockRecorder) AccessibleTaskRecord(ctx, processInstId, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccessibleTaskRecord", reflect.TypeOf((*MockService)(nil).AccessibleTaskRecord), ctx, processInstId, offset, limit)
}

// AccessibleTaskTimeline mocks base method.
func (m *MockService) AccessibleTaskTimeline(ctx context.Context, processInstId, offset, limit int) ([]engine.TaskTimelineGroup, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccessibleTaskTimeline", ctx, processInstId, offset, limit)
	ret0, _ := ret[0].([]engine.TaskTimelineGroup)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AccessibleTaskTimeline indicates an expected call of AccessibleTaskTimeline.
func (mr *MockServiceMockRecorder) AccessibleTaskTimeline(ctx, processInstId, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccessibleTaskTimeline", reflect.TypeOf((*MockService)(nil).AccessibleTaskTimeline), ctx, processInstId, offset, limit)
}

// CreateSkippedTask mocks base method.
func (m *MockService) CreateSkippedTask(ctx context.Context, processInstId int, nodeId, prevNodeId, comment string, status uint8) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSkippedTask", ctx, processInstId, nodeId, prevNodeId, comment, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSkippedTask indicates an expected call of CreateSkippedTask.
func (mr *MockServiceMockRecorder) CreateSkippedTask(ctx, processInstId, nodeId, prevNodeId, comment, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSkippedTask", reflect.TypeOf((*MockService)(nil).CreateSkippedTask), ctx, processInstId, nodeId, prevNodeId, comment, status)
}

// DeleteProxyNodeByNodeId mocks base method.
func (m *MockService) DeleteProxyNodeByNodeId(ctx context.Context, processInstId int, nodeId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProxyNodeByNodeId", ctx, processInstId, nodeId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProxyNodeByNodeId indicates an expected call of DeleteProxyNodeByNodeId.
func (mr *MockServiceMockRecorder) DeleteProxyNodeByNodeId(ctx, processInstId, nodeId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProxyNodeByNodeId", reflect.TypeOf((*MockService)(nil).DeleteProxyNodeByNodeId), ctx, processInstId, nodeId)
}

// ForceUpdateIsFinishedByNodeId mocks base method.
func (m *MockService) ForceUpdateIsFinishedByNodeId(ctx context.Context, processInstId int, nodeId string, status int, comment string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForceUpdateIsFinishedByNodeId", ctx, processInstId, nodeId, status, comment)
	ret0, _ := ret[0].(error)
	return ret0
}

// ForceUpdateIsFinishedByNodeId indicates an expected call of ForceUpdateIsFinishedByNodeId.
func (mr *MockServiceMockRecorder) ForceUpdateIsFinishedByNodeId(ctx, processInstId, nodeId, status, comment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForceUpdateIsFinishedByNodeId", reflect.TypeOf((*MockService)(nil).ForceUpdateIsFinishedByNodeId), ctx, processInstId, nodeId, status, comment)
}

// ForceUpdateIsFinishedByPreNodeId mocks base method.
func (m *MockService) ForceUpdateIsFinishedByPreNodeId(ctx context.Context, processInstId int, nodeId string, status int, comment string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForceUpdateIsFinishedByPreNodeId", ctx, processInstId, nodeId, status, comment)
	ret0, _ := ret[0].(error)
	return ret0
}

// ForceUpdateIsFinishedByPreNodeId indicates an expected call of ForceUpdateIsFinishedByPreNodeId.
func (mr *MockServiceMockRecorder) ForceUpdateIsFinishedByPreNodeId(ctx, processInstId, nodeId, status, comment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForceUpdateIsFinishedByPreNodeId", reflect.TypeOf((*MockService)(nil).ForceUpdateIsFinishedByPreNodeId), ctx, processInstId, nodeId, status, comment)
}

// GetAutomationTask mocks base method.
func (m *MockService) GetAutomationTask(ctx context.Context, currentNodeId string, processInstId int) (model.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAutomationTask", ctx, currentNodeId, processInstId)
	ret0, _ := ret[0].(model.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAutomationTask indicates an expected call of GetAutomationTask.
func (mr *MockServiceMockRecorder) GetAutomationTask(ctx, currentNodeId, processInstId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAutomationTask", reflect.TypeOf((*MockService)(nil).GetAutomationTask), ctx, currentNodeId, processInstId)
}

// GetInstanceByID mocks base method.
func (m *MockService) GetInstanceByID(ctx context.Context, processInstId int) (domain.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstanceByID", ctx, processInstId)
	ret0, _ := ret[0].(domain.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInstanceByID indicates an expected call of GetInstanceByID.
func (mr *MockServiceMockRecorder) GetInstanceByID(ctx, processInstId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstanceByID", reflect.TypeOf((*MockService)(nil).GetInstanceByID), ctx, processInstId)
}

// GetLatestProcessVersion mocks base method.
func (m *MockService) GetLatestProcessVersion(ctx context.Context, processID int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestProcessVersion", ctx, processID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestProcessVersion indicates an expected call of GetLatestProcessVersion.
func (mr *MockServiceMockRecorder) GetLatestProcessVersion(ctx, processID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestProcessVersion", reflect.TypeOf((*MockService)(nil).GetLatestProcessVersion), ctx, processID)
}

// GetProcessDefineByVersion mocks base method.
func (m *MockService) GetProcessDefineByVersion(ctx context.Context, processID, version int) (model.Process, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProcessDefineByVersion", ctx, processID, version)
	ret0, _ := ret[0].(model.Process)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProcessDefineByVersion indicates an expected call of GetProcessDefineByVersion.
func (mr *MockServiceMockRecorder) GetProcessDefineByVersion(ctx, processID, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProcessDefineByVersion", reflect.TypeOf((*MockService)(nil).GetProcessDefineByVersion), ctx, processID, version)
}

// GetProxyNodeByProcessInstId mocks base method.
func (m *MockService) GetProxyNodeByProcessInstId(ctx context.Context, processInstId int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProxyNodeByProcessInstId", ctx, processInstId)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProxyNodeByProcessInstId indicates an expected call of GetProxyNodeByProcessInstId.
func (mr *MockServiceMockRecorder) GetProxyNodeByProcessInstId(ctx, processInstId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProxyNodeByProcessInstId", reflect.TypeOf((*MockService)(nil).GetProxyNodeByProcessInstId), ctx, processInstId)
}

// GetProxyPrevNodeID mocks base method.
func (m *MockService) GetProxyPrevNodeID(ctx context.Context, processInstId int, prevNodeID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProxyPrevNodeID", ctx, processInstId, prevNodeID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProxyPrevNodeID indicates an expected call of GetProxyPrevNodeID.
func (mr *MockServiceMockRecorder) GetProxyPrevNodeID(ctx, processInstId, prevNodeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProxyPrevNodeID", reflect.TypeOf((*MockService)(nil).GetProxyPrevNodeID), ctx, processInstId, prevNodeID)
}

// GetProxyTaskByProcessInstId mocks base method.
func (m *MockService) GetProxyTaskByProcessInstId(ctx context.Context, processInstId int) (model.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProxyTaskByProcessInstId", ctx, processInstId)
	ret0, _ := ret[0].(model.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProxyTaskByProcessInstId indicates an expected call of GetProxyTaskByProcessInstId.
func (mr *MockServiceMockRecorder) GetProxyTaskByProcessInstId(ctx, processInstId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProxyTaskByProcessInstId", reflect.TypeOf((*MockService)(nil).GetProxyTaskByProcessInstId), ctx, processInstId)
}

// GetTasksByCurrentNodeId mocks base method.
func (m *MockService) GetTasksByCurrentNodeId(ctx context.Context, processInstId int, currentNodeId string) ([]model.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasksByCurrentNodeId", ctx, processInstId, currentNodeId)
	ret0, _ := ret[0].([]model.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasksByCurrentNodeId indicates an expected call of GetTasksByCurrentNodeId.
func (mr *MockServiceMockRecorder) GetTasksByCurrentNodeId(ctx, processInstId, currentNodeId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasksByCurrentNodeId", reflect.TypeOf((*MockService)(nil).GetTasksByCurrentNodeId), ctx, processInstId, currentNodeId)
}

// GetTasksByInstUsers mocks base method.
func (m *MockService) GetTasksByInstUsers(ctx context.Context, processInstId int, userIds []string) ([]model.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasksByInstUsers", ctx, processInstId, userIds)
	ret0, _ := ret[0].([]model.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasksByInstUsers indicates an expected call of GetTasksByInstUsers.
func (mr *MockServiceMockRecorder) GetTasksByInstUsers(ctx, processInstId, userIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasksByInstUsers", reflect.TypeOf((*MockService)(nil).GetTasksByInstUsers), ctx, processInstId, userIds)
}

// GetTicketIdByVariable mocks base method.
func (m *MockService) GetTicketIdByVariable(ctx context.Context, processInstId int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTicketIdByVariable", ctx, processInstId)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTicketIdByVariable indicates an expected call of GetTicketIdByVariable.
func (mr *MockServiceMockRecorder) GetTicketIdByVariable(ctx, processInstId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTicketIdByVariable", reflect.TypeOf((*MockService)(nil).GetTicketIdByVariable), ctx, processInstId)
}

// GetTraversedEdges mocks base method.
func (m *MockService) GetTraversedEdges(ctx context.Context, record []model.Task, processInstId, processId int, status uint8) (map[string][]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTraversedEdges", ctx, record, processInstId, processId, status)
	ret0, _ := ret[0].(map[string][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTraversedEdges indicates an expected call of GetTraversedEdges.
func (mr *MockServiceMockRecorder) GetTraversedEdges(ctx, record, processInstId, processId, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTraversedEdges", reflect.TypeOf((*MockService)(nil).GetTraversedEdges), ctx, record, processInstId, processId, status)
}

// IsReject mocks base method.
func (m *MockService) IsReject(ctx context.Context, taskId int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsReject", ctx, taskId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsReject indicates an expected call of IsReject.
func (mr *MockServiceMockRecorder) IsReject(ctx, taskId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsReject", reflect.TypeOf((*MockService)(nil).IsReject), ctx, taskId)
}

// ListAllTodoTasks mocks base method.
func (m *MockService) ListAllTodoTasks(ctx context.Context, userId, processName string, sortByAse bool, offset, limit int) ([]domain.Instance, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllTodoTasks", ctx, userId, processName, sortByAse, offset, limit)
	ret0, _ := ret[0].([]domain.Instance)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListAllTodoTasks indicates an expected call of ListAllTodoTasks.
func (mr *MockServiceMockRecorder) ListAllTodoTasks(ctx, userId, processName, sortByAse, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllTodoTasks", reflect.TypeOf((*MockService)(nil).ListAllTodoTasks), ctx, userId, processName, sortByAse, offset, limit)
}

// ListByStartUser mocks base method.
func (m *MockService) ListByStartUser(ctx context.Context, userId, processName string, offset, limit int) ([]domain.Instance, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByStartUser", ctx, userId, processName, offset, limit)
	ret0, _ := ret[0].([]domain.Instance)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByStartUser indicates an expected call of ListByStartUser.
func (mr *MockServiceMockRecorder) ListByStartUser(ctx, userId, processName, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByStartUser", reflect.TypeOf((*MockService)(nil).ListByStartUser), ctx, userId, processName, offset, limit)
}

// ListPendingStepsOfMyTask mocks base method.
func (m *MockService) ListPendingStepsOfMyTask(ctx context.Context, processInstIds []int, starter string) ([]domain.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPendingStepsOfMyTask", ctx, processInstIds, starter)
	ret0, _ := ret[0].([]domain.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPendingStepsOfMyTask indicates an expected call of ListPendingStepsOfMyTask.
func (mr *MockServiceMockRecorder) ListPendingStepsOfMyTask(ctx, processInstIds, starter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPendingStepsOfMyTask", reflect.TypeOf((*MockService)(nil).ListPendingStepsOfMyTask), ctx, processInstIds, starter)
}

// ListTodoTasks mocks base method.
func (m *MockService) ListTodoTasks(ctx context.Context, userId, processName string, sortByAse bool, offset, limit int) ([]domain.Instance, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTodoTasks", ctx, userId, processName, sortByAse, offset, limit)
	ret0, _ := ret[0].([]domain.Instance)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTodoTasks indicates an expected call of ListTodoTasks.
func (mr *MockServiceMockRecorder) ListTodoTasks(ctx, userId, processName, sortByAse, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTodoTasks", reflect.TypeOf((*MockService)(nil).ListTodoTasks), ctx, userId, processName, sortByAse, offset, limit)
}

// Pass mocks base method.
func (m *MockService) Pass(ctx context.Context, taskId int, comment string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pass", ctx, taskId, comment)
	ret0, _ := ret[0].(error)
	return ret0
}

// Pass indicates an expected call of Pass.
func (mr *MockServiceMockRecorder) Pass(ctx, taskId, comment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pass", reflect.TypeOf((*MockService)(nil).Pass), ctx, taskId, comment)
}

// ProcessSave mocks base method.
func (m *MockService) ProcessSave(ctx context.Context, process *model.Process) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessSave", ctx, process)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessSave indicates an expected call of ProcessSave.
func (mr *MockServiceMockRecorder) ProcessSave(ctx, process any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessSave", reflect.TypeOf((*MockService)(nil).ProcessSave), ctx, process)
}

// Reject mocks base method.
func (m *MockService) Reject(ctx context.Context, taskId int, comment string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reject", ctx, taskId, comment)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reject indicates an expected call of Reject.
func (mr *MockServiceMockRecorder) Reject(ctx, taskId, comment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reject", reflect.TypeOf((*MockService)(nil).Reject), ctx, taskId, comment)
}

// TaskInfo mocks base method.
func (m *MockService) TaskInfo(ctx context.Context, taskId int) (model.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TaskInfo", ctx, taskId)
	ret0, _ := ret[0].(model.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TaskInfo indicates an expected call of TaskInfo.
func (mr *MockServiceMockRecorder) TaskInfo(ctx, taskId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TaskInfo", reflect.TypeOf((*MockService)(nil).TaskInfo), ctx, taskId)
}

// TaskRecord mocks base method.
func (m *MockService) TaskRecord(ctx context.Context, processInstId, offset, limit int) ([]model.Task, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TaskRecord", ctx, processInstId, offset, limit)
	ret0, _ := ret[0].([]model.Task)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// TaskRecord indicates an expected call of TaskRecord.
func (mr *MockServiceMockRecorder) TaskRecord(ctx, processInstId, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TaskRecord", reflect.TypeOf((*MockService)(nil).TaskRecord), ctx, processInstId, offset, limit)
}

// Transfer mocks base method.
func (m *MockService) Transfer(ctx context.Context, taskId int, userIds []string) ([]model.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transfer", ctx, taskId, userIds)
	ret0, _ := ret[0].([]model.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Transfer indicates an expected call of Transfer.
func (mr *MockServiceMockRecorder) Transfer(ctx, taskId, userIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transfer", reflect.TypeOf((*MockService)(nil).Transfer), ctx, taskId, userIds)
}

// UpdateIsFinishedByPreNodeId mocks base method.
func (m *MockService) UpdateIsFinishedByPreNodeId(ctx context.Context, processInstId int, nodeId string, status int, comment string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIsFinishedByPreNodeId", ctx, processInstId, nodeId, status, comment)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateIsFinishedByPreNodeId indicates an expected call of UpdateIsFinishedByPreNodeId.
func (mr *MockServiceMockRecorder) UpdateIsFinishedByPreNodeId(ctx, processInstId, nodeId, status, comment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIsFinishedByPreNodeId", reflect.TypeOf((*MockService)(nil).UpdateIsFinishedByPreNodeId), ctx, processInstId, nodeId, status, comment)
}

// UpdateTaskPrevNodeID mocks base method.
func (m *MockService) UpdateTaskPrevNodeID(ctx context.Context, taskId int, prevNodeId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskPrevNodeID", ctx, taskId, prevNodeId)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTaskPrevNodeID indicates an expected call of UpdateTaskPrevNodeID.
func (mr *MockServiceMockRecorder) UpdateTaskPrevNodeID(ctx, taskId, prevNodeId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskPrevNodeID", reflect.TypeOf((*MockService)(nil).UpdateTaskPrevNodeID), ctx, taskId, prevNodeId)
}

// Upstream mocks base method.
func (m *MockService) Upstream(ctx context.Context, taskId int) ([]model.Node, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upstream", ctx, taskId)
	ret0, _ := ret[0].([]model.Node)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upstream indicates an expected call of Upstream.
func (mr *MockServiceMockRecorder) Upstream(ctx, taskId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upstream", reflect.TypeOf((*MockService)(nil).Upstream), ctx, taskId)
}
