// Code generated by eiam permgen. DO NOT EDIT.

package perm

// Dispatch 工单模板/执行单元路由
var Dispatch = struct {
	Module string
	Add    string // 创建执行单元路由 [租户级]
	Delete string // 删除执行单元路由 [租户级]
	Edit   string // 修改执行单元路由 [租户级]
	Sync   string // 复制执行单元路由 [租户级]
	View   string // 执行单元路由列表 [租户级]
}{
	Module: "ticket:dispatch",
	Add:    "ticket:dispatch:add",
	Delete: "ticket:dispatch:delete",
	Edit:   "ticket:dispatch:edit",
	Sync:   "ticket:dispatch:sync",
	View:   "ticket:dispatch:view",
}

// Manager 工单中心
var Manager = struct {
	Module         string
	FormConfig     string // 任务节点表单配置 [租户级]
	Get            string // 工单详情 [租户级]
	Graph          string // 流程轨迹图 [租户级 · 跨域: workflow]
	History        string // 历史工单 [租户级]
	MyStart        string // 我发起的工单 [租户级]
	MyTodo         string // 我的待办工单 [租户级]
	Pass           string // 同意审批 [租户级]
	ProcessRestart string // 重新启动流程 [租户级]
	Rate           string // 评价工单 [租户级 · 静默]
	Reject         string // 驳回审批 [租户级]
	Revoke         string // 撤销工单 [租户级]
	Submit         string // 提交工单 [租户级]
	Timeline       string // 流转时间线 [租户级]
	Todo           string // 所有待办工单 [租户级]
	Transfer       string // 转交审批人 [租户级]
	ViewTasks      string // 关联自动化任务 [租户级 · 跨域: task]
}{
	Module:         "ticket:manager",
	FormConfig:     "ticket:manager:form_config",
	Get:            "ticket:manager:get",
	Graph:          "ticket:manager:graph",
	History:        "ticket:manager:history",
	MyStart:        "ticket:manager:my_start",
	MyTodo:         "ticket:manager:my_todo",
	Pass:           "ticket:manager:pass",
	ProcessRestart: "ticket:manager:process_restart",
	Rate:           "ticket:manager:rate",
	Reject:         "ticket:manager:reject",
	Revoke:         "ticket:manager:revoke",
	Submit:         "ticket:manager:submit",
	Timeline:       "ticket:manager:timeline",
	Todo:           "ticket:manager:todo",
	Transfer:       "ticket:manager:transfer",
	ViewTasks:      "ticket:manager:view_tasks",
}

// Task 工单中心/自动化任务
var Task = struct {
	Module       string
	Logs         string // 执行尝试日志 [租户级 · 静默]
	Retry        string // 重试自动化任务 [租户级]
	Terminate    string // 强制终止自动化任务 [租户级]
	View         string // 自动化任务列表 [租户级]
	ViewAttempts string // 执行尝试列表 [租户级]
}{
	Module:       "ticket:task",
	Logs:         "ticket:task:logs",
	Retry:        "ticket:task:retry",
	Terminate:    "ticket:task:terminate",
	View:         "ticket:task:view",
	ViewAttempts: "ticket:task:view_attempts",
}

// Template 工单模板
var Template = struct {
	Module            string
	Add               string // 创建工单模板 [租户级]
	AddGroup          string // 创建模板分类 [租户级]
	Delete            string // 删除工单模板 [租户级]
	DeleteGroup       string // 删除模板分类 [租户级]
	Edit              string // 修改工单模板 [租户级]
	EditGroup         string // 修改模板分类 [租户级]
	Get               string // 工单模板详情 [租户级]
	RulesByWorkflowId string // 获取流程绑定模板校验链 [租户级 · 静默]
	ToggleFavorite    string // 收藏状态变更 [租户级 · 静默]
	View              string // 工单模板列表 [租户级]
	ViewByIds         string // 批量获取模板详情 [租户级 · 静默]
	ViewByWorkflowId  string // 根据流程获取模板 [租户级 · 静默]
	ViewFavorite      string // 模板收藏夹 [租户级 · 静默]
	ViewGroup         string // 查询模板分组列表 [租户级 · 静默]
	ViewGroupSummary  string // 查询模板分组摘要 [租户级 · 静默]
}{
	Module:            "ticket:template",
	Add:               "ticket:template:add",
	AddGroup:          "ticket:template:add_group",
	Delete:            "ticket:template:delete",
	DeleteGroup:       "ticket:template:delete_group",
	Edit:              "ticket:template:edit",
	EditGroup:         "ticket:template:edit_group",
	Get:               "ticket:template:get",
	RulesByWorkflowId: "ticket:template:rules_by_workflow_id",
	ToggleFavorite:    "ticket:template:toggle_favorite",
	View:              "ticket:template:view",
	ViewByIds:         "ticket:template:view_by_ids",
	ViewByWorkflowId:  "ticket:template:view_by_workflow_id",
	ViewFavorite:      "ticket:template:view_favorite",
	ViewGroup:         "ticket:template:view_group",
	ViewGroupSummary:  "ticket:template:view_group_summary",
}

// Workflow 流程管理
var Workflow = struct {
	Module              string
	Add                 string // 创建流程 [租户级]
	Delete              string // 删除流程 [租户级]
	Deploy              string // 流程发布 [租户级]
	Edit                string // 修改流程 [租户级]
	Get                 string // 流程详情 [租户级]
	View                string // 流程列表 [租户级]
	ViewAutomationNodes string // 查询流程自动化节点 [租户级 · 静默]
	ViewByIds           string // 批量获取流程详情 [租户级 · 静默]
	ViewByKeyword       string // 模糊检索流程模板 [租户级 · 静默]
}{
	Module:              "ticket:workflow",
	Add:                 "ticket:workflow:add",
	Delete:              "ticket:workflow:delete",
	Deploy:              "ticket:workflow:deploy",
	Edit:                "ticket:workflow:edit",
	Get:                 "ticket:workflow:get",
	View:                "ticket:workflow:view",
	ViewAutomationNodes: "ticket:workflow:view_automation_nodes",
	ViewByIds:           "ticket:workflow:view_by_ids",
	ViewByKeyword:       "ticket:workflow:view_by_keyword",
}
