// Code generated by eiam permgen. DO NOT EDIT.

package model

import "github.com/Duke1616/eiam/pkg/web/capability"

var (
	// Dispatch 工单模板/执行单元路由 (ticket:dispatch)
	Dispatch = capability.Model{
		Service: "ticket",
		Name:    "dispatch",
		Group:   "工单模板/执行单元路由",
		Scope:   capability.ScopeTenant,
	}
	// Manager 工单中心 (ticket:manager)
	Manager = capability.Model{
		Service: "ticket",
		Name:    "manager",
		Group:   "工单中心",
		Scope:   capability.ScopeTenant,
	}
	// Task 工单中心/自动化任务 (ticket:task)
	Task = capability.Model{
		Service: "ticket",
		Name:    "task",
		Group:   "工单中心/自动化任务",
		Scope:   capability.ScopeTenant,
	}
	// Template 工单模板 (ticket:template)
	Template = capability.Model{
		Service: "ticket",
		Name:    "template",
		Group:   "工单模板",
		Scope:   capability.ScopeTenant,
	}
	// Workflow 流程管理 (ticket:workflow)
	Workflow = capability.Model{
		Service: "ticket",
		Name:    "workflow",
		Group:   "流程管理",
		Scope:   capability.ScopeTenant,
	}
)
